### ISSUE TITLE
Вылет при нажатии кнопки "случайный релиз".

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#106]
Система: Linux 5.10.156 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Воспроизведение:
Сбой происходит только при первой установке программы. Если программу установить, запустить, подождать синхронизации релизов, а затем удалить программу и поставить заново вылета не происходит.

Устанавливаем программу в первый раз на компьютер. После установки перед запуском выключаем интернет. Это не обязательно если вы успеет нажать кнопку "Открыть карточку релиза выбранного случайным образом" до синхронизации или у вас медленная связь.
Интернет выключаем чтоб не заниматься кто кого обгонит. Видим страницу.
![anilibria](https://user-images.githubusercontent.com/11571779/207322250-2d6bf7f6-7c7a-4d3c-8aa3-6cdff882ab26.png)
Нажимаем кнопку "Открыть карточку релиза выбранного случайным образом" и программа сразу вылетает, сообщая в терминал такую ошибку:
`ASSERT: "highest > 0" in file /usr/include/qt5/QtCore/qrandom.h, line 133`

Похоже что попытка вывести то чего еще нет и приводит к ошибке.

**Comment by trueromanus** [comment]
Исправлено и войдет в версию 1.2.3.
