### ISSUE TITLE
Баги с QSettings && Window

### ISSUE THREAD

**Issue by Sepera-okeq** [anilibria/anilibria-winmaclinux#118]
**Проблема**
При работе с данным app, обнаружены баги: 

0. Добавьте блокировку на минимальные размеры окна, чтобы нельзя было случайно как-то скрыть до 0, без возможности обратно какой либо стороны растянуть окно.

1. При обычном запуске, программа пишет в реестр, что не хорошо. Из-за этого бывают приколы с тем, что если я сделаю размеры какой-то либо стороны равной 0, то при перезапуске, (как я ожидаю) будет восстановлено до нормального размера, но этого не происходит, и человеку необходимо чистить реестр.
![image](https://user-images.githubusercontent.com/54331959/212876726-899414d0-43b7-4542-a5a5-67b3ca144b1c.png)

2. При режиме portable (удивительно что не `-portable`, просьба переписать на `QCommandLineParser` парсер аргументов) программа считывает значения из реестра и записывает в него, а не создает локальный .ini файл (`QSettings` это позволяет).
И из-за этого, когда я не смог изначально исправить проблемы с размером окна, я попытался запустить в портативном режиме (что и сделало, файлы создавались относительно бинарного файла), но он считывал с реестра, что недопустимо, а должен был создать какой-нибудь .ini файл.

**Информация**
 - Type: Notebook
 - OS: Windows 11 Pro 22H2 22621.1105
 - Version App: lastest (1.2.3)

**Comment by Sepera-okeq** [comment]
P.S Рекомендую сделать [так хранение настроек](https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes), используя .ini файл и храня (в Windows например: `FOLDERID_RoamingAppData\MySoft\Star Runner.ini`)

**Comment by trueromanus** [comment]
Здравствуйте,
"Добавьте блокировку на минимальные размеры окна" - хорошо
"При обычном запуске, программа пишет в реестр, что не хорошо. Из-за этого бывают приколы с тем, что если я сделаю размеры какой-то либо стороны равной 0, то при перезапуске, (как я ожидаю) будет восстановлено до нормального размера, но этого не происходит, и человеку необходимо чистить реестр." - как изменения места хранения решит эту проблему? Если она произошла "чистить реестр" или чистить файл я думаю не будет особой разницы. И чем так "не хорош" реестр?
"При режиме portable (удивительно что не -portable, просьба переписать на QCommandLineParser парсер аргументов)" - ради одного параметра не вижу смысла внедрять QCommandLineParser, и "portable" vs "-portable" это вкусовщина.
"программа считывает значения из реестра и записывает в него, а не создает локальный .ini файл (QSettings это позволяет).
И из-за этого, когда я не смог изначально исправить проблемы с размером окна, я попытался запустить в портативном режиме (что и сделало, файлы создавались относительно бинарного файла), но он считывал с реестра, что недопустимо, а должен был создать какой-нибудь .ini файл." - портативный режим предназначен для перемещения кеша приложения. Настройки содержащиеся в реестре не относятся к кешу приложения и не переносятся с приложением и изменение места их хранения ни на что не повлияет в портативном режиме.

**Comment by Sepera-okeq** [comment]
> Если она произошла "чистить реестр" или чистить файл я думаю не будет особой разницы. И чем так "не хорош" реестр? 
  
Прежде всего, что реестр это та самая вещь, которая может сломаться от различных причин, и да лишний раз лучше туда юзера не пускать, иначе потом вас **плохими словами будут проклинать**, что из-за вашей программы что-то сломалось в реестре _**(хоть и вы и не виноваты!)**_. Реестр Windows это худшее, что в принципе придумано в Windows, так-как из-за поломки этой крайне хрупкой вещи - летит вся ось. Лучше делать более привычно и безопаснее - в виде файлов настроек в либо папки AppData и со своей папкой в Roaming, либо в принципе рядом хранить с бинарем. Уж поверьте, так лучше будет, а еще вам пользователи скажут спасибо.
  
> ради одного параметра не вижу смысла внедрять QCommandLineParser, и "portable" vs "-portable" это вкусовщина.

Я не против конечно, просто у вас уж и если по привычке делать для всех, то лучше все-таки `-portable`, так-как больше привык так обычно писать юзер из-за заданной культуры во всех программах. Это вы можете конечно делать на свой цвет и вкус, но можете и реализовать просто `("portable" || "-portable")` ;)
  
> портативный режим предназначен для перемещения кеша приложения.

Ну, я ожидал что он будет работать и так-же с настройками (те, которые в реестр в запихиваете зачем-то), чтобы можно было тестировать и проверять, не задевая основные настройки, которые лежат в релизной версии программы. Да что? Тот же кеш, как оказывается, содержит настройки и различные параметры как оказывается, например тема. Уж поверьте, так будет лучше, что портативная версия воссоздает рядом файл настроек.

**Comment by Sepera-okeq** [comment]
Кстати забыл упомянуть, кроме размеров (которые вы уже исправили), есть проблема с тем, что программа запоминает где располагается окно, и если оно вылетело за пределы экрана, то его достать невозможно. А так как, вы не реализовали Windows фичи, то его и достать никак не получится, не почистив реестр. Поэтому я бы рекомендовал не запоминать расположение приложения, так-как в этом нет никакого смысла.

Если будет время, то прикрутите обратно, что при нажатии на предпросмотр в таскбаре и нажатии ПКМ вылезает данное окно:
![image](https://user-images.githubusercontent.com/54331959/213007932-34831233-9e1c-417e-a08c-dfbaaaf38c48.png)

**Comment by trueromanus** [comment]
`Прежде всего, что реестр это та самая вещь, которая может сломаться от различных причин, и да лишний раз лучше туда юзера не пускать, иначе потом вас плохими словами будут проклинать, что из-за вашей программы что-то сломалось в реестре (хоть и вы и не виноваты!).` - Вы четвертый человек который столкнулся с проблемой при которой надо "лазить" в реестр и поменять пару значений. Я думаю некому мифическому "юзеру" о котором Вы пишите абсолютно плевать где оно храниться и как и в большинстве своем он даже не отличит значения слов реестр и файл. И Вы возводите в проблему каких-то неведомых масштабов мелкую проблему которая решается за 2 минуты даже самым малознающим пользователем с инструкцией.
`Реестр Windows это худшее, что в принципе придумано в Windows, так-как из-за поломки этой крайне хрупкой вещи - летит вся ось. Лучше делать более привычно и безопаснее - в виде файлов настроек в либо папки AppData и со своей папкой в Roaming, либо в принципе рядом хранить с бинарем. Уж поверьте, так лучше будет, а еще вам пользователи скажут спасибо. Запомните - если есть возможность хранить НЕ в реестре Windows, то так и лучше действуйте. Об этом было не раз написано в интернетиках. Если надо, могу скинуть, да и научен своим опытом.` - пользователям как я уже сказал выше абсолютно наплевать где оно храниться и в каком виде и ни о каком спасибо за это и мечтать не приходиться. Столько хейта у Вас от реестра ну давайте скидывайте Ваши страшные истории, почитаю. Вот только странно что кучи программ на Windows как писали так и продолжают писать в реестр, наверно их делают идиоты.
`Я не против конечно, просто у вас уж и если по привычке делать для всех, то лучше все-таки -portable, так-как больше привык так обычно писать юзер из-за заданной культуры во всех программах. Это вы можете конечно делать на свой цвет и вкус, но можете и реализовать просто ("portable" || "-portable") ;)` - что за культура такая? я видел программы в которых использовались куча вариантов для задания параметров с тире и без, с компоновкой буковок и с двумя тире и т.п. Может скинете ссылку где эта культура описана? И что опять за мифический "юзер" который к чему-то привык?
`Ну, я ожидал что он будет работать и так-же с настройками (те, которые в реестр в запихиваете зачем-то, да и они редактируются портативной версией, т.е по факту данная версия все-таки ломает релизную версию программы!), чтобы можно было тестировать и проверять, не задевая основные настройки, которые лежат в релизной версии программы. Да что? Тот же кеш, как оказывается, содержит настройки и различные параметры как оказывается, например тема приложения. Уж поверьте, так будет лучше, что портативная версия воссоздает рядом файл настроек, рядом с тем же кешом.` - портативный режим это для людей которые пишут программы на флешки и ходят с ними между компами. Эти настройки (размеры окна и позиция) локальные на конкретной машине потому что размеры мониторов и их количество также разное на разных компах, если Вы запишете эти настройки и сохраните на флешке то перейдя на другой комп Вы получите как раз ту ситуацию когда окно вылетело черт пойми куда за экран поэтому кеш и эти настройки разделены. То что если использовать портативную и не портативную версии одновременно и они будут писать и читать из одного места настройки размера окна я не считаю проблемой, даже если будет та маловероятная проблема ради которой Вы предлагаете что-то менять то ее легко пофиксить что сводит на нет серьзность этой проблемы. Наоборот есть куча кейсов где это в плюс даже будет, например есть человек решил с портативной переехать на обычную а тут и все настройки остались и наоборот.
`Кстати забыл упомянуть, кроме размеров (которые вы уже исправили), есть проблема с тем, что программа запоминает где располагается окно, и если оно вылетело за пределы экрана, то его достать невозможно, даже перезапустив программу. А так как, вы не реализовали Windows фичи(одно из них ниже), то его и достать никак не получится, не почистив реестр.` - эта менюшка будет если Вы выключите кастомный тулбар (соответствующая настройка в Каталоге релизов). Когда кастомный тулбар включен используется frameless окно, и для него не нашел способа решить эту проблему, если Вы знаете как то жду PR от Вас.
`Поэтому я бы рекомендовал не запоминать расположение приложения, так-как в этом нет никакого смысла, а лучше при каждом запуске программы автоматически выставлять по центру экрана.` - не поверите но другие пользователи "ожидают" что приложение будет восстанавливать позицию и размеры окна между сессиями запуска приложения.

**Comment by trueromanus** [comment]
`Ну уж простите, что у меня окно в итоге вылетело за пределы экрана монитора и обычными виндовыми хоткеями толком не работало (так-как выпилил был всего этого виндового). Уж реально, храните это как кэш. Уж я не понимаю каким боком вы все равно упрямитесь хранить все в реестре, хотя давно сказано не одним человеком и доказано: [клик1 ], [клик2 ], [клик3 (да даже в вики написано!)], [клик4]. Да и если бы вам все равно кажется, что реестр это лучшее, то он банально реализован очень плохо. Ваше решение, вы конечно можете и дальше действовать писать как вам желается` - еще раз, Вы столкнулись с проблемой что настройки сохранились c некорректными значениями и окно уплыло за экран, Вы открыли реестр и пофиксили эту проблему. Почему изменение хранение настроек из реестра в файл станет решением этой проблемы? Я прочитал все статьи и согласен что дизайн реестра плохой но не понимаю как это связано с этой проблемой в приложении? 
`но просто сейчас это выглядит так, как будто вы не понимаете в чем предъява, что допуская и ваши слова "2 минуты даже самым малознающим пользователем с инструкцией." говорят, что вам в принципе пофиг на user'а, и вы никак не читали ни msdn насчет реестра, ни другое.`- ну хорошо вот я поменял на ini файл допустим, произошла такая же проблема, и что произошло - пользователь знает где хранится этот файл? пользователь в курсе о формате ini? пользователь знает чем и как его отредактировать чтобы пофиксилось? Может есть редакторы ini файлов? ответ на все эти вопросы в 99% будет нет. Я же написал что в любом случае понадобилось бы написать инструкцию для устранения этой проблемы для пользователя и если есть инструкция то любой даже малознающий пользователь может по ней просто пройти и решить.
`Выше кинул конечно, могу еще десяток конечно кинуть, но я не думаю, что вы в принципе читать будете. История с реестром Windows - давняя история, но судя по вам, вы о ней не знакомы. Не буду как либо за это критиковать, это пусть будет вашим делом, мое лишь дело сказать о подходе, когда кроссплатформенное приложение пихает все реестр, а в остальных случаях в директории с файликами - плохо.` - "пихает" прям 5 настроек это прям конечно же "все". 
`Насчет идиотов, согласен с вами полностью на все 100%, если бы в MS задумались и сделали бы наконец-то что-то внятное и не приводящее к отказу всей оси, то я бы с вами был бы не прав и встал на их сторону!` - значит я тоже идиот и MS идиоты и еще много кто видимо.
`Ну давайте обратимся к самой классике Windows:
в cmd (deprecated) - command /help 
в powershell (current) - command -help 
Как мы знаем, от cmd.exe уже мелкомягкие уже пытаются вырезать, а больше использовать любимый PS с обвязке с Terminal.
Хоть и винде поддерживается все 4 способа(псы, если что это -, /, -- и word) , как вы сказали, но если откроем добрую msdn по PowerShell: [тык] или другую прочую статью на ней, то все любят -. А тот же / уже является устаревшим. Самый лучший пример трендов у мелкомягких - их любимое детище сборник всех консолей - [Terminal](https://learn.microsoft.com/ru-ru/windows/terminal/command-line-arguments?tabs=windows), и как вы заметили, слова они используют для конкретно либо какого-то обьекта, а не как задавать режим программы (например New-tab, либо search, и все это в PS/T)` - я открыл Вашу ссылочку и
![image](https://user-images.githubusercontent.com/9040186/213252239-027c7b3c-1842-4595-af0a-8cfc07202c0b.png)
вижу вот такой вот винегрет и это на одной странице. Культурой к сожалению и не пахнет. Ладно если для Вас это так важно то я добавил, пользуйтесь.
`Насчет этого я бы поспорил` - насчет чего Вы бы поспорили? Я это добавил потому что пользователи хотели и писали мне об этом. Если хотите можете поспорить с ними.
`у меня есть встречное предложение, чтобы не устраивать балаган нам в вдвоем:
Добавить настройки в программу:
Открывать ли окно программы в развернутом режиме при запуске программы всегда. (Да/Нет) (По умолчанию - Нет, т.е просто будет небольшое окно)
Запоминать ли расположение окна? (Да/Нет) (По умолчанию - Да, автоматически расположится там, где было до этого)`
Первая настройка зачем? Можно просто открыть на максимум и закрыть так с включенной второй настройкой.

**Comment by Sepera-okeq** [comment]
>  еще раз, Вы столкнулись с проблемой что настройки сохранились c некорректными значениями и окно уплыло за экран, Вы открыли реестр и пофиксили эту проблему. Почему изменение хранение настроек из реестра в файл станет решением этой проблемы? Я прочитал все статьи и согласен что дизайн реестра плохой но не понимаю как это связано с этой проблемой в приложении?

Я про то, что это будет легко исправить, удалив банальные строки с этим в файле или даже сам файл, отвечающий за это, и при этом не залезая в реестр, так как с ini форматом все строки, которых не хватает, автоматически можно восстанавливать в файле.

> ну хорошо вот я поменял на ini файл допустим, произошла такая же проблема, и что произошло - пользователь знает где хранится этот файл? 

Пользователи предполагают что либо лежит в %AppData%, так-как это все-таки папка для данных приложений, либо лежит рядом с бинарем (т.е например Program Files), либо в документах (Documents) или в корне %USERNAME%. Это вот самые распространенные попытки найти файлы какого-нибудь приложения, если чел не знает конкретно, где лежит, знаю по большой выборке человек (около 20к~50к человек).

> Может есть редакторы ini файлов?

Не смешите, обычный блокнот в Windows спокойно можно использовать для редактирования файла .ini, не говоря о Notepad++ или каких либо IDE.

> ответ на все эти вопросы в 99% будет нет. Я же написал что в любом случае понадобилось бы написать инструкцию для устранения этой проблемы для пользователя и если есть инструкция то любой даже малознающий пользователь может по ней просто пройти и решить.

Ладно, все таки ваш флаг в этой части, но создание интуитивности все-таки не помешало бы, так-как все-таки знать привычки обычного %username% стоит знать.

> - значит я тоже идиот и MS идиоты и еще много кто видимо.

Я это сказал со сарказмом, специально сделал _italic text_, простите, если вы не поняли ;(

> вижу вот такой вот винегрет и это на одной странице. Культурой к сожалению и не пахнет. Ладно если для Вас это так важно то я добавил, пользуйтесь.

За это вам спасибо, но насчет винегрета, я уже сказал, что Terminal и PS имеет вот данный винегрета. Но так в основном принцип такой что есть `<какая-то хрень> -аргумент`, так что да. Но вообще все-таки я люблю больше как устроено в GNU/POSIX, так что не горячитесь насчет PS, да и привел вам как в пример это.

>  - насчет чего Вы бы поспорили? Я это добавил потому что пользователи хотели и писали мне об этом. Если хотите можете поспорить с ними.

Просто у меня был опыт больше который я высказывал, люди больше для меня просили такой вариант, чем такой. Все-таки, лучше все делать в виде настроек ;)

> Первая настройка зачем? Можно просто открыть на максимум и закрыть так с включенной второй настройкой.

Чтобы например не жмякать лишную раз кнопку развернуть, если не вкючена вторая настройка. Но это как вам конечно удобно.

**Comment by Adult-Benladen** [comment]
Позвольте уж мне вмешаться как человеку не профильному зато имеющий огромный опыт по технической поддержки пользователей.
` - еще раз, Вы столкнулись с проблемой что настройки сохранились c некорректными значениями и окно уплыло за экран, Вы открыли реестр и пофиксили эту проблему. Почему изменение хранение настроек из реестра в файл станет решением этой проблемы? Я прочитал все статьи и согласен что дизайн реестра плохой но не понимаю как это связано с этой проблемой в приложении?`
По такому случаю Вы оправдываете собственную лень, задача пользователя - пользоваться а не исправлять лень разработчика и что-то там где-то исправлять. Ему проще 8 раз забить и положить. Корпоративно, это крайне вредящая разработка.

`- ну хорошо вот я поменял на ini файл допустим, произошла такая же проблема, и что произошло - пользователь знает где хранится этот файл? пользователь в курсе о формате ini? пользователь знает чем и как его отредактировать чтобы пофиксилось? Может есть редакторы ini файлов? ответ на все эти вопросы в 99% будет нет. Я же написал что в любом случае понадобилось бы написать инструкцию для устранения этой проблемы для пользователя и если есть инструкция то любой даже малознающий пользователь может по ней просто пройти и решить.`
Но в тоже время пользователя нельзя пускать в реестр, в противном случае виноватым будете всегда Вы.

**Comment by trueromanus** [comment]
@Sepera-okeq
`Я про то, что это будет легко исправить, удалив банальные строки с этим в файле или даже сам файл, отвечающий за это, и при этом не залезая в реестр, так как с ini форматом все строки, которых не хватает, автоматически можно восстанавливать в файле. Пользователи предполагают что либо лежит в %AppData%, так-как это все-таки папка для данных приложений, либо лежит рядом с бинарем (т.е например Program Files), либо в документах (Documents) или в корне %USERNAME%. Это вот самые распространенные попытки найти файлы какого-нибудь приложения, если чел не знает конкретно, где лежит, знаю по большой выборке человек (около 20к~50к человек). Не смешите, обычный блокнот в Windows спокойно можно использовать для редактирования файла .ini, не говоря о Notepad++ или каких либо IDE. Ладно, все таки ваш флаг в этой части, но создание интуитивности все-таки не помешало бы, так-как все-таки знать привычки обычного %username% стоит знать, да и как уже говорил, пускать лишний раз куда попало лучше не стоит, а гонять туда, где все по классике (про AppData) и нельзя просто так все сломать.` - Я имел ввиду что да все это прекрасно и мы с Вами если нам сказать что-то типа "Открой файлик X в appdata и удали параметры Y" разберемся и догадаемся что сделать. Но есть и пользователи которым надо прям по шагам все рассказать иначе они не поймут что надо сделать. Им надо сказать "1. Перейдите в папку Х 2. Откройте файлик Y в программе Z 3. Замените там строчку A на строчку B" и т.п.

`Я это сказал со сарказмом, специально сделал _italic text_, простите, если вы не поняли ;(` - это был тоже сарказм с моей стороны не переживайте ;)
 
`Просто у меня был опыт больше который я высказывал, люди больше для меня просили такой вариант, чем такой. Все-таки, лучше все делать в виде настроек ;)` - да опыт дело такое :)

@Adult-Benladen
`По такому случаю Вы оправдываете собственную лень, задача пользователя - пользоваться а не исправлять лень разработчика и что-то там где-то исправлять. Ему проще 8 раз забить и положить. Корпоративно, это крайне вредящая разработка.` - Ну классно теперь я еще и ленивая *опа :))

`Но в тоже время пользователя нельзя пускать в реестр, в противном случае виноватым будете всегда Вы.` - это интересная точка зрения но она правдива только если я прям сказал человеку что-то сделать в реестре и он сломал систему из-за этого но такое событие крайне маловероятно. В этом ишью автор треда сам нашел нужные значения и исправил.

В общем я создал отдельную ишью с описанием эту закрываем потому что тут много лишней болтовни. Приятно было с Вами пообщаться.
