### ISSUE TITLE
Текст пути не отображается в настройках TorrentStream

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#123]
Система: Linux 5.10.156 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Если вы используете тёмную тему для приложения, то текст с указанием пути к файлу в меню настроек TorrentStream становится невидимым.

Воспроизведение:
Укажите путь к файлу TorrentStream в пункте меню TorrentStream.
Измените тему приложения на темную.
Вернуться в меню TorrentStream.

![Screenshot_20230302_135520](https://user-images.githubusercontent.com/11571779/222409166-48d1df95-c965-4989-80e9-ddd76ecbcc58.png)
![Screenshot_20230302_133416](https://user-images.githubusercontent.com/11571779/222408228-2962ab25-17ea-4034-a14d-bba1e2e1d494.png)

**Comment by trueromanus** [comment]
Исправлено и уже в master ветке. В бинарные сборки войдет в версию 1.2.5.
