### ISSUE TITLE
Баг с видео

### ISSUE THREAD

**Issue by niallipa** [anilibria/anilibria-winmaclinux#128]
**Describe the bug**
На новых релизах видео иногда останавливается и все, пока не нажмёшь кнопку перезагрузить видео, появляется рандомно, в начале, в конце, может появиться несколько раз за видео.

Когда останавливается видео появляется кнопка включить (плей), но она ничего не делает по клику

**Device**
  Винда 10 последняя, анилибрия последний релиз, плеер VLC

**Comment by niallipa** [comment]
![изображение](https://user-images.githubusercontent.com/45980077/232337476-e03485ab-76c9-4aba-9595-3e8f65469739.png)

**Comment by niallipa** [comment]
Да, а еще, не знаю создавать ли отдельный баг, у некоторых аниме нет аватарки 
![изображение](https://user-images.githubusercontent.com/45980077/232337492-1b8ffdb6-35ab-4c80-b831-45f76cfdc8be.png)

**Comment by trueromanus** [comment]
"На новых релизах видео иногда останавливается и все, пока не нажмёшь кнопку перезагрузить видео, появляется рандомно, в начале, в конце, может появиться несколько раз за видео."
К сожалению это баг плеера VLC. Раньше приложение автоматически отслеживало такие остановки и перезагружало автоматом но такое поведение иногда приводило к тому что приложение зависало поэтому я отключил и оставил кнопку перезапуска. Остановка обычно происходит в пике нагрузки на сервера. Если это происходит слишком часто для комфортного просмотра то можете смотреть через плеер QtAv с включенным проксированием через TorrentStream.

"Да, а еще, не знаю создавать ли отдельный баг, у некоторых аниме нет аватарки"
Откройте страницу Обслуживание и нажмите на кнопки "Очистить кеш постеров". Далее перезапустите приложение. Если не помогает то на той же странице нажмите кнопку "Изменить адрес api" и выберите другой сервер например wwnd.
