### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by RC014** [anilibria/anilibria-winmaclinux#129]
После обновления Windows 11, при запуске клиента, появляется просто белое окно и дальше ничего не прогружается.
Ниже прикрепляю скриншот проблемы:
![image](https://user-images.githubusercontent.com/70579287/233800813-c3f4fd42-9470-4e08-8a5b-bfeaca55ddf7.png)

А также скрины всех недавно установленных обновлений:
![image](https://user-images.githubusercontent.com/70579287/233800870-553933aa-8a0c-43a1-aecd-dc8859dd2d92.png)
![image](https://user-images.githubusercontent.com/70579287/233800878-aa2d580a-74a7-4dd7-a113-5ab74775ecc1.png)
![image](https://user-images.githubusercontent.com/70579287/233800890-20f04904-bf2d-429e-a264-dddee5644ee2.png)

При попытке закрыть клиент, секунд через 15-20 после закрытия зависает вся система, точнее сказать все приложения продолжают работать, так как слышен звук, но картинка застывает, из чего можно сделать вывод что проблема возможно связанна с драйвером NVIDIA - Display.

К сожалению не нашёл способ откатить отдельно этот драйвер.

**Comment by trueromanus** [comment]
Можно попробовать отключить кастомный тулбар. !Если вдруг что-то не получается или выглядит не как на скриншоте то лучше перед любыми действиями киньте сюда скриншот.!
Откройте приложение regedit (найдите по поиску). Далее в верхнем текстовом поле введите путь `Компьютер\HKEY_CURRENT_USER\SOFTWARE\EmptyFlow\AnilibriaDesktopClient`. Нажмите на поле `usecustomtoolbar` ПКМ далее выберите пункт `Изменить/Edit` и в поле `Значение/Value` введите `false`. Должно получиться как на скриншоте ниже.
![image](https://user-images.githubusercontent.com/9040186/233829088-fdf67e89-fd5f-4095-9bc1-7eb83409a648.png)

**Comment by RC014** [comment]
![image](https://user-images.githubusercontent.com/70579287/233842603-a5e106b8-ac7a-4e99-9f85-66ec0cbe7b78.png)
Черный квадрат стал уже, а в остальном все по старому(((
![image](https://user-images.githubusercontent.com/70579287/233842571-329010e6-0f9f-424f-9e9c-0c98b6a2434a.png)

**Comment by trueromanus** [comment]
Запустите приложение с ключом `outputlog`. Помимо окна приложения откроется еще консольное окно. Пришлите текст из него или его скриншот пожалуйста.

**Comment by RC014** [comment]
Допускаю что я просто что-то делаю не так
Я прописал ключ следуя инструкции в интернете, на всякий случай пробовал слэш, бэкслэш и чёрточку, но консольное окно так и не появилось

![image](https://user-images.githubusercontent.com/70579287/233853297-199a7b5a-b651-49e1-80b4-22c8585198e9.png)

**Comment by trueromanus** [comment]
Без черточки :) Еще можете взять в двойные кавычки путь к файлу AniLibria.exe.

**Comment by RC014** [comment]
Консоль мелькала очень быстро, и в попытке записать сие дело в обс, я решил запустить клиент анилибрии на втором мониторе, но так как консоль все равно появлялось на первом мониторе, я назначил второй монитор главным. И вот тут началось самое интересное - всё запустилось как надо, я было обрадовался что проблема пропала сама собой, но к сожалению на первом мониторе клиент все ещё не хочет запускаться.

Единственное чем отличаются мониторы это разрешением, и что странно, клиент запускается на том у которого разрешение нестандартное.

Вот записи экрана в обоих случаях, там видно и консоль, если поставить на паузу в нужный момент.

https://user-images.githubusercontent.com/70579287/233855777-0d1260a2-4486-44d7-b972-8542915a103f.mp4

https://user-images.githubusercontent.com/70579287/233855778-1bd7a70f-ba21-425c-855e-5a44f53d2271.mp4

**Comment by trueromanus** [comment]
Может быть такое что у Вас две видеокарты и для разных мониторов используются разные видеокарты? Проверьте пожалуйста в Менеджере Устройств.

**Comment by RC014** [comment]
Нет, видеокарта одна, процессор без встроенной графики

**Comment by RC014** [comment]
Более того, я не всегда включаю второй монитор, но проблема от того не пропадает

**Comment by norduk** [comment]
Привет, попробуй полностью удалить nvidia драйвер, пусть сама windows поставить по умолчанию драйвер, после попробуй запустить приложение и если все окей пробуй обновлять уже драйвер через GeForce Experience

**Comment by trueromanus** [comment]
> Нет, видеокарта одна, процессор без встроенной графики. Тем более я не всегда включаю второй монитор (он даже перестает определяться, в настройках остается только один монитор), но баг всё равно присутствует

Хорошо попробуйте в реестре (также как и раньше) поменять настройку `ismaximaze` на значение `false`. Также как Вы меняли другое значение дальше. После этого должны появиться рамки окна хотя бы и их можно попробовать изменять. Проблема как я понимаю в том что не происходит цикл обновления содержимого в окне но изменение геометрии (размера окна) должно принудительно приводить к такому действию.

**Comment by trueromanus** [comment]
> Привет, попробуй полностью удалить nvidia драйвер, пусть сама windows поставить по умолчанию драйвер, после попробуй запустить приложение и если все окей пробуй обновлять уже драйвер через GeForce Experience

Удаление драйвера не совсем простая процедура иногда требующая установки дополнительного ПО. Конечно в теории можно попробовать но результат не гарантирован а гемороя может быть много, лучше все же не давать такие радикальные советы, спасибо.

**Comment by RC014** [comment]
Рамки окна не появились так что ничего не получается изменить.

https://user-images.githubusercontent.com/70579287/234004163-7973c4cc-5047-45f6-9256-b71149f48592.mp4

**Comment by norduk** [comment]
> > Привет, попробуй полностью удалить nvidia драйвер, пусть сама windows поставить по умолчанию драйвер, после попробуй запустить приложение и если все окей пробуй обновлять уже драйвер через GeForce Experience
> 
> Удаление драйвера не совсем простая процедура иногда требующая установки дополнительного ПО. Конечно в теории можно попробовать но результат не гарантирован а гемороя может быть много, лучше все же не давать такие радикальные советы, спасибо.

это понятно, но если проблема с драйвером nvidia (что бывает часто) то таким образом можно убедиться что проблема в нем и проста откатить на прошлый драйвер, я понимаю что совет не очень но как вариант попробовать почему бы и нет

**Comment by RC014** [comment]
> > > Привет, попробуй полностью удалить nvidia драйвер, пусть сама windows поставить по умолчанию драйвер, после попробуй запустить приложение и если все окей пробуй обновлять уже драйвер через GeForce Experience
> > 
> > 
> > Удаление драйвера не совсем простая процедура иногда требующая установки дополнительного ПО. Конечно в теории можно попробовать но результат не гарантирован а гемороя может быть много, лучше все же не давать такие радикальные советы, спасибо.
> 
> это понятно, но если проблема с драйвером nvidia (что бывает часто) то таким образом можно убедиться что проблема в нем и проста откатить на прошлый драйвер, я понимаю что совет не очень но как вариант попробовать почему бы и нет

Если других вариантов нет, мне тогда уже проще всю винду переустановить

**Comment by trueromanus** [comment]
> Рамки окна не появились так что размер не получается изменить.
Хорошо тогда давайте удалим все значения в этом списке кроме (Default) - т.е. normalX и т.п. Только аккуратней пожалуйста не надо удалять что-то за пределами этого списка.

**Comment by RC014** [comment]
Окно запустилось сразу таким маленьким
![image](https://user-images.githubusercontent.com/70579287/234038635-b2c479d0-ac17-45c1-b21b-3018d64400f1.png)

**Comment by trueromanus** [comment]
У меня закончились идеи :(

**Comment by norduk** [comment]
Слушай а попробуй установить и запустить в windows sandbox

**Comment by trueromanus** [comment]
Еще проверьте что у Вас так в панели NVIDIA
![image](https://user-images.githubusercontent.com/9040186/234304469-1b62bdb4-802f-4a23-9cc5-196c3a08ccf8.png)

**Comment by RC014** [comment]
Кэш удалил, настройки проверил
![image](https://user-images.githubusercontent.com/70579287/234336342-8c81278e-d0a2-417e-b3f4-61add4695d75.png)

**Comment by RC014** [comment]
Вот ещё один странный моментик
После того как я закрываю окно анилибрии оно уходит в "Фоновые процессы", но странно тут то что обычно оно требует меньше 1% процессора, а после закрытия 12-13%

![image](https://user-images.githubusercontent.com/70579287/234338937-fc0e7c2d-6952-4b07-93e2-7dd0b89e4dee.png)
![image](https://user-images.githubusercontent.com/70579287/234338949-62d4cbd2-7df0-430d-964e-8151255ba3aa.png)

**Comment by RC014** [comment]
> Слушай а попробуй установить и запустить в windows sandbox. Посмотрим запуститься ли в изолированном окружение

Тут два варианта: либо я очень "везучий", либо слишком рукожопый(((
И даже туториалов как это решить не нашёл

Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице
![image](https://user-images.githubusercontent.com/70579287/234341585-5bab90ab-15e6-4924-9551-91eee40bdfa2.png)

**Comment by norduk** [comment]
> > Слушай а попробуй установить и запустить в windows sandbox. Посмотрим запуститься ли в изолированном окружение
> 
> Тут два варианта: либо я очень "везучий", либо слишком рукожопый((( И даже туториалов как это решить не нашёл
> 
> Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице ![image](https://user-images.githubusercontent.com/70579287/234341585-5bab90ab-15e6-4924-9551-91eee40bdfa2.png)

Забавно сейчас проверил у себя Anilibria в песочнице тоже самое выдало, но при этом другие .exe открывает (попробовал 10 разных программ)

**Comment by RC014** [comment]
> > > Слушай а попробуй установить и запустить в windows sandbox. Посмотрим запуститься ли в изолированном окружение
> > 
> > 
> > Тут два варианта: либо я очень "везучий", либо слишком рукожопый((( И даже туториалов как это решить не нашёл
> > Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице ![image](https://user-images.githubusercontent.com/70579287/234341585-5bab90ab-15e6-4924-9551-91eee40bdfa2.png)
> 
> Забавно сейчас проверил у себя Anilibria в песочнице тоже самое выдало, но при этом другие .exe открывает (попробовал 10 разных программ)
> 
> А что за заборка или версия у тебя windows?

До этого стояла кастомная сборка с отключённой телеметрией, но я решил что стабильность системы мне дороже так что установил обычную прошку, точнее я просто запустил полное восстановление и система сама скачала официальный образ, и то что это не кастомка заметно, много каких деталей отличаются.

![image](https://user-images.githubusercontent.com/70579287/234353535-94c86c7e-d0b9-4494-a723-e0e1424f79c1.png)

**Comment by trueromanus** [comment]
> Вот ещё один странный моментик
> После того как я закрываю окно анилибрии оно уходит в "Фоновые процессы", но странно тут то что обычно, будучи открытым, оно требует меньше 1% процессора, а после закрытия 12-13%

Потому что оно продолжает работать, т.е. это не краш как таковой  а просто нарушение цикла окна для винды.

> Кэш удалил, настройки проверил, без изменений

Предыдущие версии проверяли?

> Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице

Чтобы запускалось в песочнице надо включать какие-то настройки, не помню какие. Что за ПО он предлагает поставить если нажать на Yes?

**Comment by RC014** [comment]
> Предыдущие версии проверяли?
> 
Да, ещё до того как открыл обсуждение, пробовал несколько более старых, чтобы наверняка
> 
> Чтобы запускалось в песочнице надо включать какие-то настройки, не помню какие. Что за ПО он предлагает поставить если нажать на Yes?
Ничего не происходит елси нажать Yes или No, окно просто пропадает, хотя один человек на стаковерфлоу сталкивался с такой-же проблемой и у него после нажатия No приложение запускалось без проблем.

**Comment by norduk** [comment]
> > > > Слушай а попробуй установить и запустить в windows sandbox. Посмотрим запуститься ли в изолированном окружение
> > > 
> > > 
> > > Тут два варианта: либо я очень "везучий", либо слишком рукожопый((( И даже туториалов как это решить не нашёл
> > > Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице ![image](https://user-images.githubusercontent.com/70579287/234341585-5bab90ab-15e6-4924-9551-91eee40bdfa2.png)
> > 
> > 
> > Забавно сейчас проверил у себя Anilibria в песочнице тоже самое выдало, но при этом другие .exe открывает (попробовал 10 разных программ)
> > А что за заборка или версия у тебя windows?
> 
> До этого стояла кастомная сборка с отключённой телеметрией, но я решил что стабильность системы мне дороже так что установил обычную прошку, точнее я просто запустил полное восстановление и система сама скачала официальный образ. То что это не кастомка заметно, много каких деталей отличаются.
> 
> ![image](https://user-images.githubusercontent.com/70579287/234353535-94c86c7e-d0b9-4494-a723-e0e1424f79c1.png)

У тебя Insider Preview версия, попробуй найти оригинальный образ windiws 11 вроде можно взять с офф сайта, и установи на virtualbox или vmware и протестируй)

**Comment by RC014** [comment]
> > > > > Слушай а попробуй установить и запустить в windows sandbox. Посмотрим запуститься ли в изолированном окружение
> > > > 
> > > > 
> > > > Тут два варианта: либо я очень "везучий", либо слишком рукожопый((( И даже туториалов как это решить не нашёл
> > > > Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице ![image](https://user-images.githubusercontent.com/70579287/234341585-5bab90ab-15e6-4924-9551-91eee40bdfa2.png)
> > > 
> > > 
> > > Забавно сейчас проверил у себя Anilibria в песочнице тоже самое выдало, но при этом другие .exe открывает (попробовал 10 разных программ)
> > > А что за заборка или версия у тебя windows?
> > 
> > 
> > До этого стояла кастомная сборка с отключённой телеметрией, но я решил что стабильность системы мне дороже так что установил обычную прошку, точнее я просто запустил полное восстановление и система сама скачала официальный образ. То что это не кастомка заметно, много каких деталей отличаются.
> > ![image](https://user-images.githubusercontent.com/70579287/234353535-94c86c7e-d0b9-4494-a723-e0e1424f79c1.png)
> 
> У тебя Insider Preview версия, попробуй найти оригинальный образ windiws 11 вроде можно взять с офф сайта, и установи на virtualbox или vmware и протестируй)

Звучит вроде логично, но подозреваю что на виртуалке все запустится, это и заранее понятно. Проблема скорее всего в каких-то моих индивидуальных настройках, что-то не так в регистре, с кэшем и тд потому что баг переехал вместе с личными файлами и настройками винды

**Comment by trueromanus** [comment]
Попробуйте скачать и запустить вот это приложение https://github.com/trueromanus/ArdorQuery/releases/download/0.0.7/windows.amd64-0.0.7.zip. Это другое мое приложение на той же технологии сделано, просто для сбора информации, будет ли работать.

**Comment by RC014** [comment]
> Попробуйте скачать и запустить вот это приложение https://github.com/trueromanus/ArdorQuery/releases/download/0.0.7/windows.amd64-0.0.7.zip. Это другое мое приложение на той же технологии сделано, просто для сбора информации, будет ли работать.

![image](https://user-images.githubusercontent.com/70579287/234358869-922d2d6b-c6dc-49b1-a593-b23cf797d129.png)

**Comment by trueromanus** [comment]
Работает, значит все же какая-то особенность именно AniLibria. Еще вопрос, установлен ли у Вас VLC плеер?

**Comment by norduk** [comment]
> > > > > > Слушай а попробуй установить и запустить в windows sandbox. Посмотрим запуститься ли в изолированном окружение
> > > > > 
> > > > > 
> > > > > Тут два варианта: либо я очень "везучий", либо слишком рукожопый((( И даже туториалов как это решить не нашёл
> > > > > Такая красота выскакивает когда пытаюсь запустить анилибрию в песочнице ![image](https://user-images.githubusercontent.com/70579287/234341585-5bab90ab-15e6-4924-9551-91eee40bdfa2.png)
> > > > 
> > > > 
> > > > Забавно сейчас проверил у себя Anilibria в песочнице тоже самое выдало, но при этом другие .exe открывает (попробовал 10 разных программ)
> > > > А что за заборка или версия у тебя windows?
> > > 
> > > 
> > > До этого стояла кастомная сборка с отключённой телеметрией, но я решил что стабильность системы мне дороже так что установил обычную прошку, точнее я просто запустил полное восстановление и система сама скачала официальный образ. То что это не кастомка заметно, много каких деталей отличаются.
> > > ![image](https://user-images.githubusercontent.com/70579287/234353535-94c86c7e-d0b9-4494-a723-e0e1424f79c1.png)
> > 
> > 
> > У тебя Insider Preview версия, попробуй найти оригинальный образ windiws 11 вроде можно взять с офф сайта, и установи на virtualbox или vmware и протестируй)
> 
> Звучит вроде логично, но подозреваю что на виртуалке все запустится, это и заранее понятно. Проблема скорее всего в каких-то моих индивидуальных настройках, что-то не так в регистре, с кэшем и тд потому что баг переехал вместе с личными файлами и настройками винды. Конечно-же возможно проблема в самой инсайдер версии, но я не готов пересаживаться на обычную ради анилибрии, тут есть фичи которые мне очень удобны

Пробуй тогда чистить систему от мусора и т.д 
могу посоветовать для чистки [https://github.com/builtbybel/CleanmgrPlus](url)

**Comment by RC014** [comment]
> Работает, значит все же какая-то особенность именно AniLibria. Еще вопрос, установлен ли у Вас VLC плеер?

Перед переустановкой винды был установлен, сейчас установлю снова

**Comment by RC014** [comment]
> > Работает, значит все же какая-то особенность именно AniLibria. Еще вопрос, установлен ли у Вас VLC плеер?
> 
> Перед переустановкой винды был установлен, сейчас установлю снова

Установка VLC не помогла

**Comment by norduk** [comment]
Еще как вариант можно поиграться с process hacker что бы понять что происходит с процессами

**Comment by trueromanus** [comment]
Попробуйте поставить вот это приложение и проверить драйвера OpenGL. Рендеринг в приложении идет через OpenGL и если оно не рендериться то явно стоит копать в эту сторону. Возможно у Вас не стоит драйвера или надо его обновить.

https://support.zivid.com/en/latest/getting-started/software-installation/gpu/check-opengl-driver.html

**Comment by trueromanus** [comment]
Драйвера можно скачать либо с установочного диска вашей машины, либо как вариант можно поискать их на сайте производителя машины(в комплекте идут как graphics card или что-то в таком духе). Еще как вариант можно попробовать [тут](https://developer.nvidia.com/opengl-driver) скачать но там чето нет 11 винды.

**Comment by RC014** [comment]
> [тут](https://developer.nvidia.com/opengl-driver)
Тут я попробовал скачать версию для 10 и при установке комп зависает(((

**Comment by RC014** [comment]
Но в любом случае дальше уже мои проблемы, не стоит Вам тратить на это время, дело то не в Вашем приложении
