### ISSUE TITLE
Не работает скрыть приложение, MacOS

### ISSUE THREAD

**Issue by norduk** [anilibria/anilibria-winmaclinux#130]
При нажатии на иконку" Минимизировать окно в панель задач"  не прячет само приложение
Приходиться пользоваться горячими клавишами или через сам dock. Проблема была замечена еще на версии приложение 1.2.4

Ver MacOS: 13.3.1
Ver App: 1.2.5

![Screenshot 2023-04-24 at 00 56 35](https://user-images.githubusercontent.com/2527653/233868513-6fd835bf-01b3-4880-8dcc-aebce19498c5.png)
![Screenshot 2023-04-24 at 00 56 49](https://user-images.githubusercontent.com/2527653/233868566-1cbb979a-2ef7-4819-9fd8-ba790218de04.png)

**Comment by trueromanus** [comment]
Откройте настройки на странице "Каталог релизов" и выключите настройку "Использовать кастомный тулбар" после перезапустите приложение.
