### ISSUE TITLE
Краш программы, MacOS

### ISSUE THREAD

**Issue by norduk** [anilibria/anilibria-winmaclinux#131]
Если в каталоге релизов начать быстро листать в низ то приложение закрывается с ошибкой.

![Screenshot 2023-04-24 at 01 21 11](https://user-images.githubusercontent.com/2527653/233869440-ddd4494c-949a-4431-b85e-ffffedcac58c.png)

Ver MacOS: 13.3.1
Ver App: 1.2.5

Вот сам лог из системы MacOS, где лежать сами логи программы я не нашел.
[AniLibria-2023-04-24-011100.txt](https://github.com/anilibria/anilibria-winmaclinux/files/11305098/AniLibria-2023-04-24-011100.txt)

**Comment by trueromanus** [comment]
Быстро листать каким образом и что, можете добавить подробностей?

**Comment by norduk** [comment]
Если ползунком начать быстро спускать в низ то страница зависает на пару секунд, а после уже вылетает в ошибку 
![Screenshot 2023-04-24 at 14 11 48](https://user-images.githubusercontent.com/2527653/233981296-501e598e-5f36-40a2-84c5-0d912644dc04.png)

**Comment by trueromanus** [comment]
Понял но пока не смог воспроизвести.

**Comment by trueromanus** [comment]
Попробуйте открыть страницу `Обслуживание` и нажать на кнопку `Очистить кеш постеров`

**Comment by norduk** [comment]
> Попробуйте открыть страницу `Обслуживание` и нажать на кнопку `Очистить кеш постеров`
 Да я пробовал после 2 раза и он отработал нормально, вот что у меня сейчас получилось, я сейчас Очистил кеш постеров и попробовал опять и он опять крашнул, как я понял если кеш постеров есть он отрабатывает нормально, но если их очистить он начинает вылетать.

**Comment by trueromanus** [comment]
Видимо проблема в загрузке постеров в кеш. Попробую разобратся.
