### ISSUE TITLE
Вместо torrent файла скачивается html 

### ISSUE THREAD

**Issue by KnightMurloc** [anilibria/anilibria-winmaclinux#138]
**Describe the bug**
при скачивании torrent файла через приложение скачивается html файл по видимому от cdn.

**To Reproduce**
 - скачать torrent для любого релиза

**Device**
 - Manjaro Linux
 - последняя с стабильная версия из aur

**Additional context**
при скачивании с сайта скачивается коректный torrent файл.

**Comment by trueromanus** [comment]
Сейчас зеркала испытывают проблемы. Вы можете перейти на другой сервер для этого перейдите на страницу "Обслуживание", нажмите на кнопку "изменить адрес api" и выберите в поле "выбрать сервер" значение wwnd.  Далее перезапустите приложение.
