### ISSUE TITLE
Интеграция с MyAnimeList / Shikimori (АвтоЭкспорт Списка Просмотренного)

### ISSUE THREAD

**Issue by ShadowMax** [anilibria/anilibria-winmaclinux#146]
### Light Version
Для начала можно добавить автоэкспорт просмотренных Аниме/Серий на основные крупные сайты (со списком просмотренного аниме).
Для себя выделил 3 таких сайта: 
- https://myanimelist.net/
- **https://shikimori.me/**
- https://anilist.co/

### Big Bold Version
Возродить былое величие Shikimori!  (╯°□°）╯︵ ┻━┻

Интеграция:
- Добавление личной страницы шикимори в приложение.
- Добавление системы оценок.

_Старый Шики для меня был примером лучшего сервиса, где сочетались:_
1. _Просмотр_
2. _Оценивание_
3. _Ведение своих Списков просмотренного и Личного Рейтинга_
4. _Ачивки_
5. _Поиск друзей по предпочтениям в аниме (на основе рейтинга просмотренного)_
6. _Рекомендации схожих тайтлов, на основе просмотренного._
7. _и т.д._

**Comment by trueromanus** [comment]
Это интерсное предложение но реализация его в приложении крайне маловероятна. Чтобы это сделать нужно сделать отдельный сервис в который интегрировать вышеупомянутые сервисы. Почему именно так?
- Необходимо интегрировать API каждого сервиса а все они разные и с разными возможностями
- Нужно создавать базу соотстветвия релизов. Надо искать по именами или еще чему-то неисключено что даже руками проставлять т.е. это труд. Плюс никаких гарантий что любой из них (сайтов) переобуется и изменит что-то у себя что потребует заново пересоздавать эту базу

Итого делать вышеупомнянутое в приложении крайне затруднительно и очень накладно да и впринципе нецелесообразно. Чтобы реализовать эту задумку надо делать отдельный сервис который будет внутри себя аккумулировать и реализовывать интеграцию со всеми требуемыми сайтами и содержать базу соответствия релизов а наружу только торчали бы функции по экспорту просмотренного и другого необходимого функционала. Я бы может и взялся за такое но я итак много чего делаю а время какбы не бесконечное. Было бы классно если бы Вы или кто-то из Ваших знакомых занялся этим сервисом чтобы я впоследствии интегрировал этот сервис в приложение.

**Comment by ShadowMax** [comment]
@trueromanus А где храниться информация о просмотренных сериях? Мне нужно перенести их на новое устройство.
Я недавно только понял, что это походу только локальные данные, так? Всегда думал, что это закрепляется за аккаунтом🤔

**Comment by trueromanus** [comment]
@ShadowMax, 
"А где храниться информация о просмотренных сериях? Мне нужно перенести их на новое устройство." - она храниться локально, для того чтобы ее перенести есть специальные функции на странице Обслуживание. Кнопка "Бэкап кеша приложения" чтобы сделать бэкап, после скопировать файлы на другую машину и на ней выполнить функцию "Восстановить из бэкапа".
"Я недавно только понял, что это походу только локальные данные, так? Всегда думал, что это закрепляется за аккаунтом" - в текущей версии сайта и API такой функции нет, соответственно в приложении ее тоже нет поэтому все храниться локально. В новом сайте и API такая функция появиться но когда его выкатят пока неизвестно.

**Comment by trueromanus** [comment]
Теперь поддерживается написание расширений на JavaScript для создания интеграций вроде этой. Подробнее [тут](https://github.com/anilibria/anilibria-winmaclinux/blob/master/extensions.md)
