### ISSUE TITLE
Баг Кнопки Каталога Релизов

### ISSUE THREAD

**Issue by ShadowMax** [anilibria/anilibria-winmaclinux#148]
К сожалению не могу пока точно описать, когда он возникает, но иногда **при нажатии на кнопку каталога релизов**, она **переносит тебя на последний просматриваемый релиз**, а вот уже с этой страницы **нету возможности перейти в _общий каталог_**.

- Может стоит назначить клавише "Каталог релизов" функцию непосредственного перехода на начальную страницу (вместо последнего открытого релиза)? 
Если раньше это было в некоторой степени критично из-за возможности случайно закрыть нужный релиз, то сейчас существует перелистывание на предыдущую страницу, что решает этот вопрос. 
Как думаете?

**Comment by trueromanus** [comment]
Ошибка исправлена и войдет в версию 1.2.10
