### ISSUE TITLE
Вылет MacOS-Windows

### ISSUE THREAD

**Issue by norduk** [anilibria/anilibria-winmaclinux#153]
Добрый день, столкнулся с вылетом приложения. Когда захожу на релиз anime (Красноволосая принцесса Белоснежка 2 сезон) и нажимаю смотреть он сразу же вылетает, но если нажать смотреть онлайн то он открывает.
Причем все это происходит как на MacOS, так и на Windows.
Пробовал на версиях приложение 1.2.10 и 11 все то же самое.

MacOS 14
Windows 11 pro

https://github.com/anilibria/anilibria-winmaclinux/assets/2527653/9e5e4550-f717-4b21-aa9f-66545ee4c14f

**Comment by trueromanus** [comment]
Проблема из-за того что нумерация не с 1 серии. Исправление войдет в версию 1.2.12.
