### ISSUE TITLE
Не работает воспроизведение видео на arch linux

### ISSUE THREAD

**Issue by imartemy1524** [anilibria/anilibria-winmaclinux#158]
**Описание проблемы**
При попытке воспроизвести любую серию выскакивает следующая ошибка:

```
Warning: "No decoder available for type 'application/x-hls'."
qml: InvalidMedia
Error: "Your GStreamer installation is missing a plug-in."
```

**Шаги вопроизведения**
1) Установить приложение через aur.
2) Открыть просмотр какого-нибудь аниме.
3) Увидеть баг. 

**Желаемый результат**
Все необходимые плагины/драйверы скачиваются при установке пакета и всё работает из коробки.

**Screenshots**
![image](https://github.com/anilibria/anilibria-winmaclinux/assets/41122604/45dbb929-be18-46ca-9557-6789476e2675)

**Device**
 OS: Arch Linux x86_64 
Host: GF63 Thin 11UD REV:1.0 
Kernel: 6.6.3-arch1-1 
Resolution: 1920x1080 
DE: Plasma 5.27.10 
WM: kwin 
CPU: 11th Gen Intel i5-11400H (12) @ 4.500GHz 
GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
Memory: 11849MiB / 15698MiB

**Comment by imartemy1524** [comment]
Не помогло :(
![image](https://github.com/anilibria/anilibria-winmaclinux/assets/41122604/f6c25cd2-e9d6-4dc6-a7f5-9ed0932780c1)

P.S. По-моему, стоит все необходимые декодеры заранее пихать в зависимости к пакету...

**Comment by imartemy1524** [comment]
А вот это помогло:
`sudo pacman -S gst-plugins-bad`

**Comment by trueromanus** [comment]
> P.S. По-моему, стоит все необходимые декодеры заранее пихать в зависимости к пакету...
@imartemy1524 Вы можете написать мейнтейнеру пакета в AUR о том что этого пакета не хватает.
