### ISSUE TITLE
Нерабочая синхронизация релизов при сборке из исходного кода

### ISSUE THREAD

**Issue by quantumde1** [anilibria/anilibria-winmaclinux#170]
**Describe the bug**
При сборке приложения из сурсов с гитхаба и последующем запуске, приложение пытается синхронизировать релизы. Но выдается ошибка о невозможности этого.
**To Reproduce**
На Alpine Linux 3.19/edge попытаться собрать и запустить.
**Expected behavior**
Все должно работать, но не может.
**Device**
 - OS: Alpine Linux
 - Version: edge(3.20.0_alpha20240315)
 - App version: latest git

**Additional context**
в терминале есть следующие логи:
```
Cache location:  "/home/user/.local/share/EmptyFlow/AnilibriaDesktopClient"
VLC-Qt "Unknown" initialised
Using libvlc version: "3.0.20 Vetinari"
libvlc Error: "No active audio output"
libvlc Error: "No active audio output"
libvlc: cannot resolve  port 554 : Name does not resolve
libvlc: cannot connect to :554
libvlc: Connection failed
libvlc: VLC could not connect to ":554".
libvlc: Your input can't be opened
libvlc: VLC is unable to open the MRL ''. Check the log for details.
TorrentStream path not correct
count parsed pages  0
qrc:/main.qml:746: Error: drawImage(), type mismatch
libvlc Error: "No active audio output"
libvlc Error: "No active audio output"
qrc:/main.qml:746: Error: drawImage(), type mismatch
qrc:/main.qml:746: Error: drawImage(), type mismatch
qrc:/main.qml:746: Error: drawImage(), type mismatch
count parsed pages  0
```

**Comment by yashelter** [comment]
+ .zip windows 1.2.15, тоже не работает синхронизация

**Comment by quantumde1** [comment]
> * .zip windows 1.2.15, тоже не работает синхронизация

видать отвал API. Щас чекну код, мб сделаю пулл реквест

**Comment by quantumde1** [comment]
все, баг пофикшен. Можно его увидеть в группе в тг, не мы одни такие. Дублирую сюда на всякий, авось кому поможет:
```
Всем у кого не работает, пробуйте менять настройки API на странице обслуживание между умолчанием и wwnd (Кнопка изменить адрес API и далее либо кнопку Умолчание или Выбрать сервер и далее выбрать пункт wwnd). Также стоит попробовать (вы)включить VPN и другие средства обхода если вышеупомянутый шаг не помог. После изменения настроек API они применяются только после перезапуска приложения!
```

**Comment by yashelter** [comment]
> все, баг пофикшен. Можно его увидеть в группе в тг, не мы одни такие. Дублирую сюда на всякий, авось кому поможет:
> 
> ```
> Всем у кого не работает, пробуйте менять настройки API на странице обслуживание между умолчанием и wwnd (Кнопка изменить адрес API и далее либо кнопку Умолчание или Выбрать сервер и далее выбрать пункт wwnd). Также стоит попробовать (вы)включить VPN и другие средства обхода если вышеупомянутый шаг не помог. После изменения настроек API они применяются только после перезапуска приложения!
> ```

Теперь всё отлично, благодарю uwu
