### ISSUE TITLE
Добавьте статус в discord(можно будет включить в настройках)

### ISSUE THREAD

**Issue by Andrew-Zex** [anilibria/anilibria-winmaclinux#176]
как пример кода, можно использовать [Этот репозиторий](https://github.com/dhanax26/C---Discord-RPC)

**Comment by trueromanus** [comment]
Теперь поддерживается написание расширений на JavaScript для создания интеграций вроде этой. Подробнее [тут](https://github.com/anilibria/anilibria-winmaclinux/blob/master/extensions.md)
