### ISSUE TITLE
При попытке запуска последней версии приложения - ошибка

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [anilibria/anilibria-winmaclinux#180]
![image](https://github.com/anilibria/anilibria-winmaclinux/assets/61359286/0d58b48c-eac2-4c4c-9deb-0cec98f9e4cf)
Проверенные версии: 1.2.17, 1.2.16
Система: Windows 10 22H2 (ReviOS 10 23.12)

**Comment by trueromanus** [comment]
https://t.me/desktopclientanilibria/603
