### ISSUE TITLE
from C# to qt - very pity and bad idea

### ISSUE THREAD

**Issue by mzayarnyuk** [anilibria/anilibria-winmaclinux#181]
Здравствуйте, данное приложение не поддерживается.
Подробности читайте в разделе [Важное объявление](https://github.com/anilibria/anilibria-win#%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5).
Актуальное на текущий момент приложение можно найти [тут](https://github.com/anilibria/anilibria-winmaclinux#anilibriaqt).

_Originally posted by @trueromanus in https://github.com/anilibria/anilibria-win/issues/52#issuecomment-1154187003_

**Comment by trueromanus** [comment]
И что Вы хотели этим сказать?
