### ISSUE TITLE
Потеря информации о просматриваемых сериалах при обновлении

### ISSUE THREAD

**Issue by Survolog** [anilibria/anilibria-winmaclinux#191]
При обновлении приложения с версии 2.2.20 на версию 2.2.21 заметил исчезновение информации о текущих просмотренных сериях.
У меня отображение просматриваемых сериалов включено по умолчанию взамен обзора всех сериалов.
После обновления вместо просматриваемых сериалов получилось пустое окно.
При этом осталась информация о скрытых сериалах, а также текущая метка времени просмотра серии, если найти сериал вручную в общем обзоре.

В описании к релизу нашёл на вид связанное пояснение:
"Полный переход на серверные отметки о просмотрах".
Для обновления приложения в стабильной ветке дистрибутива с версии 2.2.20 хотелось бы, чтобы информация не потерялась.
Возможно ли перенести её на сервер?

**Comment by trueromanus** [comment]
"В описании к релизу нашёл на вид связанное пояснение:"
Собственно ответ есть в слудеющих предложениях:
Полный переход на серверные отметки о просмотрах. Начиная с этой версии отметки просмотра будут работать как и избранное т.е. источником истины будут не локальные отметки а те что на сервере лежат. Также переделал целиком весь внутренний механизм работы с отметками о просмотрах, надеюсь сильно ничего не сломал. **И еще не забудьте синхронизировать свои локальные отметки на сервер в прошлой версии потому что в этой версии и далее такого функционала не будет.**
Пункт "Каталог релизов" > "Управление просмотренным" > "Синхронизировать локальный просмотр"
Подробнее можно почитать [тут](https://t.me/desktopclientanilibria/642)

**Comment by Survolog** [comment]
Принял.
Возможно, наилучшим вариантом было бы наличие отдельного легаси скрипта, делающего синхронизацию.
Тогда я мог бы вызвать его единожды при обновлении пакета с версий меньше 2.2.20 или хотя бы вывести сообщение о его существовании.

В любом случае спасибо за программу.

**Comment by trueromanus** [comment]
> Возможно, наилучшим вариантом было бы наличие отдельного легаси скрипта, делающего синхронизацию.
Я к сожалению не настолько крут чтобы сделать скрипт для этого. На bash-е наверно врядли получиться тут надо много парсить json и потом раскладывать по структурам и сортировать. На python наверно можно было бы но я не силен в python-е. Если я набросаю скрипт на C#, сможете перевести его в python или еще какой-нибудь скрипт?

**Comment by Survolog** [comment]
Увы, я только .spec файлы пишу под конкретный дистрибутив. Это bash.
Не знаю, смогу ли использовать C# на линуксе. Ни разу не делал ничего подобного.
Интернет подсказывает использовать dotnet run --no-build script.cs
В моём дистрибутиве есть dotnet. Видимо, я смогу попробовать задействовать скрипт на C#.

Но может скрипт на C# понадобится кому-нибудь на ОС windows?
Сам не использую её.

На линуксе под json немного использовал jq в bash для парсинга сайтов с целью автоматизации выяснения последней версии.

Раз не просматривается возможности типа "взять по горячим следам коммиты, сложить в файл и сделать скрипт", то может стоит отложить вопрос, чтобы изучить к нему интерес?
Если же интереса не наберётся, то и делать скрипт или программу синхронизации будет незачем.

**Comment by trueromanus** [comment]
Хорошо, изучу вопрос может придумаю что-нибудь

**Comment by Keleth** [comment]
> > Возможно, наилучшим вариантом было бы наличие отдельного легаси скрипта, делающего синхронизацию.
> 
> Я к сожалению не настолько крут чтобы сделать скрипт для этого. На bash-е наверно врядли получиться тут надо много парсить json и потом раскладывать по структурам и сортировать. На python наверно можно было бы но я не силен в python-е. Если я набросаю скрипт на C#, сможете перевести его в python или еще какой-нибудь скрипт?

Если будет рабочий, пусть даже на C#, думаю переписать-то во что-то альтернативное найдется способ.

**Comment by trueromanus** [comment]
@Keleth
> Если будет рабочий, пусть даже на C#, думаю переписать-то во что-то альтернативное найдется способ.
Уже есть рабочий вариант в прошлой версии не требующий никаких скриптов. Скрипт это скорее резервный вариант.

**Comment by Survolog** [comment]
Попробовал конвертнуть скрипт C# в bash через ГигаЧат в телеграме.
Зависимости - jq и curl.
Попробовал немного отладить, но отправки данных через curl дело пока не дошло.

1. Что за "V2token", я не определил. У меня есть в файле userconfiguration.cache "v2token", и он пустой. Быть может что-то поменялось в системе аторизации, либо это самодеятельность гигачата.
2. Добавка echo ${result_ids[@]} перед save_models выдаёт мне много квадратных скобок без чего-либо внутри. Очевидно, так быть не должно. Где-то я недоотладил содержимое цикла "# Сортируем элементы по sortOrder", а может проблема и где-то выше.

```
#!/bin/bash

# Проверяем наличие переменной окружения CACHE_PATH
if [[ -z "$CACHE_PATH" ]]; then
  echo "Переменная окружения CACHE_PATH должна быть определена и содержать путь к папке, где хранятся кэш-файлы Anilibria.Qt."
  exit 1
fi

# Чтение файла seenmark.cache
old_seen_marks=($(jq -r '.[]' "$CACHE_PATH/seenmark.cache"))

if (( ${#old_seen_marks[@]} == 0 )); then
  echo "Не найдены старые метки просмотра или они пусты!"
  exit 1
fi

# Преобразуем старые метки в массив объектов
declare -A old_marks_map
for mark in "${old_seen_marks[@]}"; do
  release_id=$(echo $mark | cut -d '.' -f1)
  seria=$(echo $mark | cut -d '.' -f2)
  old_marks_map[$release_id]+="$seria "
done

# Чтение файла metadata
count_episodes=$(jq -r '.countEpisodes' "$CACHE_PATH/metadata")

# Обрабатываем каждый эпизод
result_ids=()
for (( i = 0; i < count_episodes; i++ )); do
  # Чтение файлов episodes*.cache
  episodes=$(jq -c '.[]' "$CACHE_PATH/episodes$i.cache")

  while read -r episode; do
    release_id=$(echo "$episode" | jq -r '.releaseId')

    if [[ -n ${old_marks_map[$release_id]} ]]; then
      items=$(echo "$episode" | jq -r '.items[] | select(.sortOrder != null) | [.id, .sortOrder]')

      # Сортируем элементы по sortOrder
      sorted_items=($(sort -t ' ' -k2n <<<"$items"))
      IFS=' ' read -ra old_marks <<< "${old_marks_map[$release_id]}"
      for old_mark in "${old_marks[@]}"; do
        if (( old_mark < ${#sorted_items[@]} )); then
          result_ids+=("${sorted_items[old_mark * 2]}")
        fi
      done

    fi
  done < <(printf '%s\n' "$episodes")
done

if (( ${#result_ids[@]} == 0 )); then
  echo "Не найдено ни одного эпизода для синхронизации!"
  exit 0
fi

# Чтение userconfiguration.cache
v2token=$(jq -r '.V2token' "$CACHE_PATH/userconfiguration.cache")

if [[ -z "$v2token" ]]; then
  echo "Токен v2 отсутствует в конфигурации!"
  exit 0
fi

# Отправляем данные на сервер
save_models=$(jq -nc '{Time: 0, IsWatched: true, ReleaseEpisodeId: $item}' --argjson item "${result_ids[@]}" | jq -sc '.')
curl -X POST \
     -H "Authorization: Bearer $v2token" \
     -H "Content-Type: application/json" \
     -d "$save_models" \
     https://anilibria.top/api/v1/accounts/users/me/views/timecodes
```

Попробую всё же запустить исходный скрипт C# через dotnet, как появится возможность, и если никто не дочинит скрипт bash раньше. Но из-за пустого v2token сомневаюсь, что скрипт C# у меня вообще сможет отправить данные.

Всем удачи!

**Comment by trueromanus** [comment]
> 1. Что за "V2token", я не определил. У меня есть в файле userconfiguration.cache "v2token", и он пустой. Быть может что-то поменялось в системе аторизации, либо это самодеятельность гигачата.

**Также есть требование чтобы пользователь был авторизован, иначе как мы сохраним что-то.** В этом параметре будет содержаться токен авторизованного пользователя в приложении. Если он пустой может быть Вы либо не поставили одну из версий с новым API либо не авторизовались в приложении.

> Добавка echo ${result_ids[@]} перед save_models выдаёт мне много квадратных скобок без чего-либо внутри. Очевидно, так быть не должно. Где-то я недоотладил содержимое цикла "# Сортируем элементы по sortOrder", а может проблема и где-то выше.

Возможно стоит проверить содержимое `sorted_items`

**Comment by Keleth** [comment]
> @Keleth @Survolog Вообщем накидал скрипт на C#. Для работы требуется передать в переменную окружения CACHE_PATH полный путь к папке с кешем. Также есть требование чтобы пользователь был авторизован, иначе как мы сохраним что-то.
> 
> ```cs
> using System.Net.Http.Json;
> using System.Text;
> using System.Text.Json;
> using System.Text.Json.Serialization;
> ```

Ух, последний раз я C# правда 10 лет назад видел... и оно было внешне попроще )
Что я понял, мы должны из seenmark.cache каждый элемент разбить по точке (получаем *release_id* / *seria*), потрогать метадату на предмет количества эпизодов и далее добиваем данными из episodesХ.
Однако вот чего пока не смог окончательно осознать, это конечного формата json, который надо в итоге получить.
Вроде как выглядит примерно так:

``` json
{ "time":0, "is_watched": true, "release_episode_id":  "XXX"}
```
И вот именно далее я поплыл с пониманием доставания этого *release_episode_id*, но подозреваю, что должно быть значение id (uuid) из items соответствующего эпизода (*sortOrder* == *seria*, которую зачитали из seenmarks)?
т.е. в результате там должен быть uuid, который мапится вот как-то так (я тут сам запутаное понаписал), но кажется что так.
Прав-ли я? )

**Comment by Keleth** [comment]
``` python
#!/usr/bin/env python3
import json
import requests
import sys
from pathlib import Path


cache_path = Path.home() / ".local" / "share" / "EmptyFlow" / "AnilibriaDesktopClient"
v2token = None
old_seen_marks = []
old_seen_releases = []
metadata = None
request = []


def read_token():
    global v2token
    with open(cache_path / 'userconfiguration.cache') as f:
        data = json.load(f)
        v2token = data['v2token']


def read_old_seen_marks():
    global old_seen_marks
    global old_seen_releases
    with open(cache_path / 'seenmark.cache') as f:
        data = json.load(f)
        for item in data:
            x = item.split(".")
            old_seen_marks.append({"release_id": int(x[0]), "seria": int(x[1])})
            old_seen_releases.append(int(x[0]))


def read_metadata():
    global metadata
    with open(cache_path / 'metadata') as f:
        metadata = json.load(f)


def prepare_request():
    global metadata
    global request
    global old_seen_marks
    for i in range(0, int(metadata['countEpisodes'])):
        print("Обрабатываем эпизод: " + str(i))
        episodes = None
        f_name = 'episodes' + str(i) + '.cache'
        with open(cache_path / f_name) as f:
            episodes = json.load(f)
        for episode in episodes:
            if episode['releaseId'] not in old_seen_releases:
                continue
            series = []
            for om in old_seen_marks:
                if om['release_id'] == episode['releaseId']:
                    series.append(om['seria'])
            print(series)
            sorted_items = sorted(episode['items'], key=lambda d: d['sortOrder'])
            for sort in sorted_items:
                if sort['sortOrder'] not in series:
                    continue
                request.append({'time': 0, 'is_watched': True, 'release_episode_id': sort['id']})


def send_request():
    global request
    headers = {'Authorization': f'Bearer {v2token}'}
    response = requests.post('https://anilibria.top/api/v1/accounts/users/me/views/timecodes',
                             json=request, headers=headers)
    if response.status_code != 200:
        print("не удалось отправить данные")
        print(response.content)
        sys.exit(5)


# ----------


read_token()
if v2token is None or v2token == '':
    print("Пользователь не авторизован на сервисе")
    sys.exit(1)

read_old_seen_marks()
if len(old_seen_marks) == 0:
    print("Не найдены старые метки просмотра или они пусты!")
    sys.exit(2)

read_metadata()
if metadata is None:
    print("Не удалось прочитать данные о эпизодах")
    sys.exit(3)

print("Найдено " + str(metadata['countEpisodes']) + " эпизодов")

prepare_request()
if len(request) == 0:
    print("Нет данных для отправки сервису")
    sys.exit(4)

send_request()
print("Данные синхронизированы")

```

**Comment by trueromanus** [comment]
@Keleth 
> И вот именно тут я поплыл с пониманием доставания этого release_episode_id, но подозреваю, что должно быть значение id (uuid) из items соответствующего эпизода (sortOrder == seria, которую зачитали из seenmarks)?
т.е. в результате там должен быть uuid, который мапится вот как-то так (я тут сам запутаное понаписал), но кажется что так.
Прав-ли я? )

Тут все правильно, есть документация по API по этой [ссылке](https://anilibria.top/api/docs/v1#/%D0%90%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82%D1%8B%20%3A%3A%20%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B8%20%3A%3A%20%D0%9C%D0%BE%D0%B5%20%3A%3A%20%D0%9F%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D1%8B/33f11bb339154eb2fe8a2c88628c8244). Да надо прочитать старый формат где записывались номера серий и найти идентификаторы соответствующих серий из нового формата который иметь уникальный идентификатора в формте uuid.

**Comment by Keleth** [comment]
@trueromanus 
Ага, значит вроде все так.

**Comment by Keleth** [comment]
@Survolog собрал версию 2.2.21, и в просмотренных появились отправленные данные. 
Питоновый скрипт можно применять.

**Comment by Survolog** [comment]
@trueromanus @Keleth спасибо!
Добавил python вариант скрипта в пакеты в виде файла anilibria-db-uploader.
Кому надо - запустит, либо скопирует из этой темы и запустит.
Думаю, этого достаточно.
