### ISSUE TITLE
Инерция прокручивания

### ISSUE THREAD

**Issue by WaffleLapkin** [anilibria/anilibria-winmaclinux#20]
На текущий момент инерция при скроллинге релизов слишком большая, из-за чего очень легко случайно пролистать несколько страниц, вместо половины. Было бы неплохо её уменьшить.

**Comment by trueromanus** [comment]
Уменьшил, проверь стало ли лучше.

**Comment by WaffleLapkin** [comment]
Стало значительно лучше, хотя на мой вкус всё равно многовато

**Comment by trueromanus** [comment]
Можете попробовать вручную подогнать нужное число а потом скажете какое было наиболее конфортно :).

В файле src/Views/Releases.qml на 1325 строчке
```js
scrollview.maximumFlickVelocity = scrollview.maximumFlickVelocity - 1000;
```
На линуксе вроде 2500 оригинальная инерция т.е. просто увеличивайте число 1000 постепенно пока нужный уровень комфорта не будет найден :) но число не должно превывать 2500 иначе вообще крутить не будет.

**Comment by trueromanus** [comment]
Все еще актуально? Может сделать настройку?

**Comment by WaffleLapkin** [comment]
Да, ещё актуально. Пока просто не нахожу времени на эксперименты. Надеюсь на днях смогу поэкспериментировать и доложить результаты :P

**Comment by WaffleLapkin** [comment]
Поигрался с этой настройкой и пришёл к выводу что из доступного примерно 1000-1100 самое удобное. Но возник вопрос: а зачем вообще инерция? Покрутил подобные места на разных сайтах/приложениях (гитхаб, анилибрия, телега...) — везде инерция нулевая, а скорость прокрутки больше.

А то даже с 1000-1100 получается что инерция слишком большая, а крутится всё равно как черепаха :D по крайней мере так ощущается.

**Comment by trueromanus** [comment]
Ну я вообще специально ее (инерцию) не добавлял, это контрол для скролирования такой видимо с заделом на мобилы где такое считается нормой :(.
Я еще покручу может получиться что-то с этим сделать, если нет то оставлю среднее от твоего диапазона.

**Comment by trueromanus** [comment]
Ничего не вышло :( Поставил 1050 как среднее.
