### ISSUE TITLE
Need add new icon.

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#22]
Необходима версия иконки в разрешении 48x48, [поскольку](https://github.com/anilibria/anilibria-winmaclinux/blob/9a1f97fca0103741d8248b103e54161b567dfc21/src/AniLibria.pro#L26) вместо неё сейчас используется версия 32х32.

**Comment by trueromanus** [comment]
Добавил, еще пофиксил 16 и 32, были указаны картинки с двойными размерами т.е. это были не настоящие 16 и 32.
