### ISSUE TITLE
Split main.qml file

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#24]
Заметил, что в проекте присутствует лишь один *.qml файл и он слишком уж большой. Предлагаю разделить его на несколько частей (на 3 уж точно можно, если верить моим глазам). Это позволит не только повысить читабельность, но и поможет новым контрибьюторам лучше ориентироваться в компонентах проекта.

**Comment by trueromanus** [comment]
В проекте с 10 файлов qml :) просто они в папках /controls и /views

**Comment by Samsuper12** [comment]
Ох, не заметил. Полез сразу на плюсокод смотреть и подумал, что main.qml единственный в своём роде. 

Посмотрел остальные. Да... он теперь кажется не таким большим, если сравнивать с остальными.
