### ISSUE TITLE
Old SIGNAL/SLOT connections in C++ code.

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#25]
В современном Qt можно не использовать макросы SLOT/SIGNAL и указывать связываемые компоненты подобным образом:

`connect(&Obj1, &Obj1::signal, &Obj2, &Obj2::slot_or_lamda)`

**Comment by Samsuper12** [comment]
Завтра ещё несколько ПР'ов наделаю, поскольку вижу некоторые упущения при передаче QString(и не только) по значению, что приводит к созданию временных переменных == снижению производительности, например.

**Comment by trueromanus** [comment]
Хорошо когда больше пары глаз, да в одном классе забыл переобуться на новый вариант.
Спасибо за наводку 😉

**Comment by trueromanus** [comment]
Все везде просмотрел, больше не осталось таких. PR-ы жду 😉
