### ISSUE TITLE
GPL 3.0

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#26]
Согласно лицензии, указанной в заголовке сообщения, каждый файл исходного кода должен иметь в хедере маленький фрагмент лицензии, где указывается не только ссылка на полную версию лицензии, но и закрепляется авторство за человеком, написавшим этот код. Помимо этого вносятся ещё имена тех, кто редактировал.

Не пойми скверно, себя записывать не буду, но код по идее могут легко украсть (патентные тролли существуют, увы).
См. [линк](https://www.gnu.org/licenses/gpl-3.0.ru.html), а если быть точнее, то последний пункт _"How to Apply These Terms to Your New Programs"_.

**Comment by trueromanus** [comment]
Да я знал об этом это просто обычно занимаюсь такими вещами где-то в конце перед первым релизом. Ну может и пора уже заняться.
Кстати в qml тоже надо добавлять или это за разметку сойдет?

**Comment by Samsuper12** [comment]
Да, в QML тоже надо, это ведь является Вашей интеллектуальной собственностью.
