### ISSUE TITLE
noexcept вездесущий

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#27]
Решил всё же спросить про такую ситуацию: много методов не вызывают исключения в процессе работы, а значит им спокойно можно ставить noexcept спецификатор и все от этого получат плюс, ибо время компиляции снизится и производительности прибавится. Всё по Скотту Мейерсу.

Однако! Хедер превращается в нечто подобное ([Скрин](https://priscree.ru/img/635370582d413a.png)). Что думаете по этому поводу?

**Comment by trueromanus** [comment]
Я вообщем то не против.

**Comment by Samsuper12** [comment]
Хорошо. Задам тогда ещё один вопрос: код писали единолично? Стиль слегка отличается местами.

**Comment by trueromanus** [comment]
Да я писал один, стиль разный потому что я изучал с++11. Я давно не писал на с++ вот решил вернуться к истокам :)

**Comment by Samsuper12** [comment]
Не знаю, читали ли Вы [эту](https://habr.com/ru/post/166113/) статью, но в ней есть весьма интересные подходы, которые я с радостью использую. 

Так вот, там в одном из предпоследних пунктов рекомендуют отказаться от методов get/set в пользу использования публичных членов класса. Что думаете?
Пример:
было `int order() const && void setOrder(const int order) noexcept`
стало `public: int Order`

Если желаете, можете сказать "на Ваше усмотрение" и не буду подобное спрашивать впредь.

**Comment by trueromanus** [comment]
Я понимаю в чем соль но на мой взгляд это нарушает инкапсуляцию. С одной стороны это однотипный код но если завтра понадобиться добавить какой-то функционал, например проверять в order уникальность или добавлять к нему какое-то число это прийдется делать в куче других мест а прямое использование будет ломать state этого поля в классе иначе зачем вообще использовать классы можно ограничиться структурами? Я использую классы потому что предполагаю что вышеупомянутые вещи будут иметь место в будущем.

**Comment by Samsuper12** [comment]
Поэтому и спрашивал. Хорошо, понял.

Не хочется создавать отдельную исую для этого, поэтому скажу здесь: давно хотелось создать подобное приложение, благодаря которому можно и в соло аниме посмотреть без браузера и ещё сделать это с друзьями. Нечто такое есть в гаррис моде на серверах-кинотеатрах. Поэтому данный проект меня заинтересовал. Если у Вас есть конкретные задачи, то можете оформлять иссуи на меня, а я в свою очередь буду их выполнять.

**Comment by trueromanus** [comment]
А можно по подробней что значит "ещё сделать это с друзьями". Я если честно не в теме про гаррис мод. Интересно узнать что Вы имели ввиду.

А по поводу помощи то не вопрос, все открыто, любая помощь принимается.
По поводу того что взять, я предлагаю следующий подход, я думаю большую часть времени будут открытые ишью поэтому если что приглянулось то Вы можете брать и делать. Если вдруг ишью не будет то достаточно спросить у меня или предложить свою идею через ишью, все обсуждаемо. В ишью если что не понятно лучше спросить :).
На текущий момент помимо того что уже записано в ишью есть еще большая задачка отдельную страница для так сказать внешнего плеера, т.е. логика работы с управлением плеером остается но вот только настоящий плеер будет находиться где-то еще и связываться с приложение посредством webchannel-а. Пример я в приложении запустил сервачок а допустим на телике открыл вебраузер который в свою очередь подключился к приложению и просто выступает в качестве удаленного плеера, все управление происходит внутри приложения но смотрю я в браузере телика. Клиентом не обязательно должен быть браузер это просто пример.

**Comment by Samsuper12** [comment]
Прошу прощения. "ещё сделать это с друзьями" - некий онлайн кинотеатр, в котором пользователи могут создавать лобби (закрытые\открытые) и смотреть какие-то аниме синхронно. Если брать в пример дискорд, то некий аналог голосовых каналов.

Пойду создам ишью, появилась весьма интересная идея.

**Comment by trueromanus** [comment]
Да интересная идея, я записал на будущее, надо будет проработать возможность такого. И если в этом ишью все то закрывай.
