### ISSUE TITLE
Личный кабинет.

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#28]
Каждый пользователь шикимори, умеющий работать с языками разметки, способен создать собственный стиль как для оформления сайта, так и для личного кабинета.

Это ведь вполне реализовать и в приложении Анилибрии, причем без особых усилий. 
Можно сделать примерно так: у пользователя имеется определенное место на сервере для html, css и js (можно, к слову, в будущем реализовать поддержку и других языков разметки). Когда человек в приложении заходит в личный кабинет, то загружаются эти файлы в webview. Помимо этого, можно указывать в этих файлах и цвета/стили для общего оформления приложения.

**Comment by trueromanus** [comment]
К сожалению api для личного кабинета пока нет :(. Можно конечно фейкануть через версию сайта но это все как-то костыльно. Как минимум надо договориться с другими ребятами об этом.
Для начала у пользователя имеется место на чьем сервере, своем или нашем или анилибрии? 
Идея про стили интересная но зачем нам web технологии у нас же толстый клиент? Просто раз у нас толстый клиент то решать по максимуму вещей через c++/qt/qml и только если никак больше то через webview. Да и qml поддерживает большое подмножество css стилей на худой конец можно и qml подгрузить :) хоть и не безопасно. Можно qml файл положить в папку приложения например или что-то в таком духе.
Да и если честно нам нужен тогда не webview а webengineview потому что первый не поддерживает никакой интеграции, а она нам понадобиться и в конечном итоге у нас получится решение типа [electron](https://www.electronjs.org/) :).

**Comment by Samsuper12** [comment]
Какой сервер? Не знаю даже, можно аналибрии или какой-то отдельный. Скорее отдельный для пущей безопасности.

Вот про qml не знаю. Слишком уж много доступа через него получить можно.

Знаю электрон. Страшная во всех смыслах штука...

Тогда оставляем ишью на будущее? Личный кабинет в любом случае придется делать, вдруг тут люди оставят предложения/идеи.

**Comment by trueromanus** [comment]
Ага, оставим на будущее, как прикрутят в api сразу сделаем и в приложении.

**Comment by trueromanus** [comment]
Теперь в приложении есть возможность менять стили и иконки (в будущем и много чего еще) даже не зная css и html на странице "Менеджер Тем". Темы хранятся в виде файлов но есть возможно и сохранить в некое общее хранилище, может не так просто как на Шикимори но все же есть. Также личный кабинет как таковой тоже теперь есть на странице "Моя Анилибрия" возможно не в том виде как на Шикимири но в каком-то виде это оно. Поэтому я считаю что данное ишью можно закрывать. Если есть еще идеи или вопросы смело переоткрывайте это ишью.
