### ISSUE TITLE
Внешний плеер

### ISSUE THREAD

**Issue by trueromanus** [anilibria/anilibria-winmaclinux#30]
Добавить специальную страницу внешнего плеера где можно будет управлять удаленным плеером в внешнем декстопном клиенте или браузере.
Сделать возможным поддержку одновременного просмотра нескольких клиентов, через внешний сервер вероятно, с полной синхронизацией позиции потока воспроизведения чтобы можно было смотреть удаленно с друзьями одно и тоже видео.

**Comment by trueromanus** [comment]
@WaffleLapkin Проверьте пожалуйста что пакет ставиться корректно, я добавил новую зависимость в программу.

**Comment by WaffleLapkin** [comment]
У меня собирается нормально.

**Comment by trueromanus** [comment]
Спасибо, тогда пускаем в релиз :)
