### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by Samsuper12** [anilibria/anilibria-winmaclinux#31]
В кутях есть замечательный класс [QSettings](https://doc.qt.io/qt-5/qsettings.html), благодаря которому можно сохранять пользовательские настройки в файл. 
Думаю, добавление пользовательских настроек будет вполне адекватным решением не только на этапе между темной темой и личным кабинетом, но и сейчас хотя бы для сохранения позиции и размера окна.

**Comment by trueromanus** [comment]
Она есть и используется для сохранения токена пользователя в Classes/Services/applicationsettings.cpp. В перспективе да туда пойдут сохранения размеров окна и прочие локальные настройки.

**Comment by trueromanus** [comment]
Сохранение размера окна и позиции между сеансами прикручено 😉
