### ISSUE TITLE
Могу сделать редизайн

### ISSUE THREAD

**Issue by jacklisov** [anilibria/anilibria-winmaclinux#32]
Привет! Напиши мне в телеграме, обсудим редизайна, а то этот выглядит топорно.

Мой телеграм: @jacklisov

**Comment by trueromanus** [comment]
Привет! Что мешает вести обсуждение здесь? Это публичный проект и ладно вещи сугубо технические которые не все могут обсуждать но дизайн вещь понятная для всех. Я готов обсудить вопрос нового не "топорного" дизайна. Начнем обсуждение здесь а дальше как пойдет к тому же остальные пользователи могут вставлять свои пять копеек.
Итак какие у Вас есть предложения по дизайну?

**Comment by jacklisov** [comment]
https://www.figma.com/file/1dunHCT0oGnC6xJuE05c4p/Untitled?node-id=0%3A1

Набросал за час, жду критику

**Comment by trueromanus** [comment]
Я не совсем понял идеи поэтому несколько уточнений:
- Что это такое снизу и почему среди этого есть пункт "Поддержать проект"?
- Сортировка по чему то подразумевает две настройки - поле и направление у Вас второго я не увидел
- Вы считаете что постера и микроскопически написанного названия с годом и сезоном достаточно в списке релизов?
- "История посещений" - вообще пункт называется не так но да ладно, т.е. Вы предлагаете сделать выпадайкой я прав?
- А где все остальное что есть на этой странице?

**Comment by jacklisov** [comment]
Я сказал, что еще только набросал. Начну с конца. Я не добавил все функции так, как я просто элементарно не понимаю, что за что отвечает в приложение. (Также и про сортировку). Если надо еще что-то добавить, только скажи. Для превью релиза, названия и года выпуска - предостаточно. Не стоит перегружать пользователя. А про поддержать проект, это кнопка должна быть на виду. Про историю посещений прошу уточнить.

**Comment by jacklisov** [comment]
Также дополню, снизу - это новое меню (по новой задумке дизайна, стоит отказаться от фона кнопки).

**Comment by trueromanus** [comment]
"Я не добавил все функции так, как я просто элементарно не понимаю, что за что отвечает в приложение." - дак может с этого и начать, разобраться как работает приложение и какие в нем функции. Дизайн для этого приложения взят не из пустого места а из другого приложения анилибрии для win10 которое существует уже больше года и которое уже прошло весь путь от "ужасающего дизайна" до "удобное приложение". Если есть вопросы какие идеи сейчас лежат в текущем дизайне и почему это сделано так или иначе задавайте.
"Для превью релиза, названия и года выпуска - предостаточно. Не стоит перегружать пользователя." Не стоит путать Ваше личное предпочтение и предпочтение пользователей, вся та информация которая рядом с релизом была добавлена по просьбам этих самых пользователей. Идея тут как я увижу всю информацию о релизе, есть ли он в моем избранном сколько серий и кто озвучивал, многие выбирают в поиске старые релизы и им не удобно каждый из них прокликивать и смотреть что же там в нем. Вариант когда один постер удобен только если список горизонтальный и постер отвечает только на часть инфы например как сделано в кинотеатрах там есть заголовок группы ну незнаю "Комедии" а дальше ниже идут уже в линию постеры. К тому же на список завязано много функционала например множетсвенный выбор, быстрые действия и т.п. Очень опрометчиво утверждать что все это можно весело выкинуть и решить за пользователя что он перегружен.
"А про поддержать проект, это кнопка должна быть на виду." Почему она должна быть на виду? Зачем она должна маячить по сути все время пребывания в программе? Это настолько важный вещь что надо совать пользователю её все время? В приложении win10 была отдельная страница на эту кнопку и по статистике за больше года существования приложения на нее перешли не более пары сотен раз а вот все остальное на странице каталог релизов нажимают 10к раз за месяц. Надо уметь правильно расставлять приоритеты, кто захочет задонатить найдет как это сделать.
"Также дополню, снизу - это новое меню" - задумка странная, потому что пунктов меню будет много, уже сейчас их 5 и их количество будет только расти в будущем и они банально не будут вмещаться туда. Да и само расположение меню странное в десктопных приложениях меню либо сверху, либо слева/справа внизу я не могу припомнить что меню было, ну разве только переключалки каких-нибудь разделов. Т.е. это какой-то странный ux который люди привыкшие к другому просто будут не понимать, есть что-то сверху что-то снизу что из них меню?
"Про историю посещений прошу уточнить." - дак это вопрос к Вам - что это такое?

**Comment by jacklisov** [comment]
Мое дело предложить. Я сделал дизайн не на ОСНОВЕ ЛИЧНЫХ ПРЕДПОЧТЕНИЙ, а на ОСНОВЕ ПОСЛЕДНИХ ТЕНДЕНЦИЙ. Меню снизу включает только самые важные функции приложения. Это аналог NavigationBar в Android (почитай про него на досуге и поймешь почему так мало функций). В оригинальном приложение отсутствуют даже элементарные подписи элементов. Все нагружено. Удобства ноль. Я еще пользовался приложением для win 10, но сам же лично ушел из-за неудобства. Скажу так, я не первый год в дизайне и прекрасно умею раставлять приорететы. Даже так возьмем, ты хотябы понимаешь почему кнопки цветный, почему растояние между элементами достаточно большое, почему я так мало указал в информации постера. Здесь везде есть что-то что нужно так или иначе пользователю и разработчику. А про историю просмотров - это что-то наподобии последних релизов куда заходил пользователь. Также запомни НИКОГДА  не думай сразу о олдах приложения. ВПЕРВУЮ очередь думай о новичках. Дизайн сейчас непонятен и грамоздок.

**Comment by trueromanus** [comment]
"Я сделал дизайн не на ОСНОВЕ ЛИЧНЫХ ПРЕДПОЧТЕНИЙ, а на ОСНОВЕ ПОСЛЕДНИХ ТЕНДЕНЦИЙ" - согласен тут я перегнул, поэтому извиняюсь. Что это за такие последние тенденции можно ссылочки увидеть?

"Меню снизу включает только самые важные функции приложения. Это аналог NavigationBar в Android (почитай про него на досуге и поймешь почему так мало функций)" - у нас не Android и не мобильное приложение, там (в android-е) это решает определенные проблемы которые связаны с маленькими экранами и мобильными устройствами ввода, даже в приложениях на android tv этой штуки уже нет, а десктопные приложения находятся именно в этой нише т.е. приложения расчитанные на большие экраны.

"В оригинальном приложение отсутствуют даже элементарные подписи элементов." там есть тултипы почти на всех "кнопках иконках" так что упрек мимо но ок я услышал Вас.

"Я еще пользовался приложением для win 10, но сам же лично ушел из-за неудобства." - Вместо того чтобы сообщить о проблемах просто обсираем приложение и перестаем его использовать. Вот это нормальный подход :)

"Скажу так, я не первый год в дизайне и прекрасно умею раставлять приорететы." - предложение про приоритеты к Вам вообще никак не относилось, я писал о своем опыте связанном со статистикой что нужно уметь расставлять приоритеты на базе статистики использования.

"Даже так возьмем, ты хотябы понимаешь почему кнопки цветный, почему растояние между элементами достаточно большое, почему я так мало указал в информации постера. Здесь везде есть что-то что нужно так или иначе пользователю и разработчику. " - я готов услышать развернутый и конструктивный ответ.

"Все нагружено. Удобства ноль." "Дизайн сейчас непонятен и грамоздок." - давайте еще больше таких крайне информативных предложений которые четко указывают на проблему о которой Вы хотите сказать.

Итого что у нас в сухом остатке по проблемам которые я пока смог понять от Вас:
- У иконок в вертикальной панели нет текста - решается расширением панели до такой ширины чтобы влезали текстовые названия для каждой иконки. Возможно опционально скрывать/показывать по кнопке, надо подумать.
- Слишком много информации в ячейке релиза - решается добавление настройки при включении которой в ячейке остаются только постеры.
- Слишком много кнопок в вертикальной панели - решается возможностью скрывать часть и/или все кнопки. Если скрыты все кнопки то вся панель выпиливается.

И напоследок, больше не надо употреблять в беседе крикокапсы, обращаться ко мне на ты а также указывать в ультимативной форме что кому делать, иначе наша беседа закончится так и не начавшись.

**Comment by jacklisov** [comment]
Если так посудить, то можно и с вашими пожеланиями, но все же, вы сами сказали про "надо основываться на статистике", но при этом все иконки и функции без приоритетно показываете на главном экране.

Про тултипы. Я скачивал ваше приложение под Линукс и ни одной, хотябы малейшей подсказки нет.

Про цвета, нужно выставлять цвета, каждый цвет так или иначе действует на психику человека. Например, красные это больше цвет опасности и поэтому кнопка уведомления красная, намекая пользователю на то что, здесь ему делать нечего.

Про тенденции. Сейчас в тренде минимализм и легкость (растояние между элементами). Сейчас в дизайне не приветствуется перегрузка контентом.

Про NavigationBar. Это пример названия, этого места. Оно имеет ряд удобств и ряд неудобств, но на мой взгляд оно наиболее подходит здесь, потому что так, можно предоставить больше сокращеного превью релизов.

**Comment by RadiationX** [comment]
Хочу ворваться в ваше обсуждение дизайна.
Вижу некоторое кол-во проблем, готов по каждой расписать вместе с возможными решениями.
Например много скриншотов сюда будет трудно вставить, как минимум читать потом это будет трудно.
Так-же некоторые замечания имеют "общий" характер, которые еще перекликаются с "частными".
Как это лучше описать? Как оформить? Просто текстом? Со скринами?

**Comment by trueromanus** [comment]
@RadiationX Как удобней можно описать, можно здесь, можно на внешнем ресурсе а здесь ссылку, можно архив прикрепить. Наличие скриншотов и по возможности максимальное описание приветствуется.

**Comment by RadiationX** [comment]
Хочется описать проблемы, с которыми я столкнулся при первом знакомстве с программой. Практически все предложенные решения составлял исходя из опыта использования других популярных приложений, т.к. по их примеру можно понять, какие паттерны поведения более простые и знакомые для пользователей.
На данный момент к приложению нужно добавлять мануал по использованию (unix/linux way), и было бы неплохо уйти от этого.

##### Начнем с UX.
1. С первого взгляда не понятно зачем "switch" в верхнем левом углу. Только через минут 30 понял, что он отвечает за мультиселект карточек.
Вообще мультиселект сделан крайне непривычно, первый раз вижу такой паттерн выделения.
Плюс к этому, кнопка "быстрые действия" вносит непонятность в механизм выбора карточки.
**Решение:** Для данной программы больше подойдёт паттерн, когда при клике ПКМ (или просто долгим нажатии) по карточке всплывает контекстное меню с возможными действиями, там-же расположить пункт "выбрать", по которому запускается режим мультиселекта карточек. Так получится чуть дольше, но это поведение вроде гораздо интуитивнее для новых юзеров. 
Мультиселект будет отменяться при клике мимо карточки.
В таком случае можно будет убрать "switch" в левом верхнем углу. И вместо него уже отображать название текущего экрана (перенести его с правого края).

2. В приложении, в одном окне, повторяются одинаковые иконки без привязки к какому-то контексту.
    1. Иконка "звездочка" в боковом меню - вроде как используется для контекстного действия с карточкой релиза. 
    **Решение:** скрыть в всплывающее контекстное меню, как описано в 1 пункте.
    2. Иконка "глаз" в боковом меню - используется для отметки о просмотре.
	**Решение:** скрыть в всплывающее контекстное меню карточки.
        1. Не вижу смысла там держать "удалить все отметки", т.к. это не контекстное действие.
        **Решение:** Переместить этот пункт в например в настройки.
    3. Иконка "колокольчик" в боковом меню - используется для отображения уведомлений в всплывающем окне. Но честно говоря не понимаю почему там отображаются просто список "счетчиков" каких-то изменений. В моем понимании уведомлений, там должен быть список релизов, в которых были этим изменения.
    **Решение 1:** Сделать то, есть сейчас хотя-бы кликабельным, чтобы открывался список релизов с изменениями.
    **Решение 2:** Отображать список релизов, в которых были изменения, например группированными списками.
    **Решение 3:** Убрать и заменить тем, что находится в верхнем меню. (В пункте 3 будет об этом).
    4. Иконка "колокольчик" в правом нижнем углу - отображает кол-во синхронизаций и лог синхронизаций. Зачем это пользователю?
    **Решение:** Убрать.

3. Глобальное состояние одного списка релизов, которое меняется от "поиска по названию", "фильтра", любого переключения пунктов в верхнем меню.
Например если сделать поиск по фильтру, еще поиск по названию и переключиться например на расписание, то будет отображен пустой список. Как бы круто, да, отфильтровалось всё как надо, но я хотел просто посмотреть расписание и теперь мне нужно очистить все фильтры и т.д. чтобы посмотреть расписание.
**Решение:** Разбить разные разделы приложения на независимые "экраны"/"фрагменты", которые отображают только свою часть данных.
Т.к. боковое меню по сути является основным, то иконки с разделами приложения перенести в него.
    1. Тогда появляется такая проблема с тем, что нужно как-то выбирать подпункты в разделах (например "история" и "история просмотров"). 
    **Решение:** В "фрагментах" добавить "табы"/"переключатели"/"кнопки", которые будут отвечать за свой контент.
    2. Сортировка сейчас глобальная, как быть с "фрагментами"?
    **Решение:** Добавить сортировку в каждый фрагмент отдельно.
    3. Что делать с фильтром?
    **Решение:** Перенести кнопку по которой будут открываться настройки фильтра во внутрь фрагмента.
    4. Что делать с "уведомлениями" в боковом меню?
    **Решение:** Точно так-же как в пункте 3.1 - подпункты добавить уже в самом "фрагменте", возможно индикатором об изменениях у каждого пункта.

4. Выезжающее боковое меню выглядит лишним. 
    **Решение:** Перенести эти пункты в боковое меню.
    1. Пункты "YouTube" и "Войти" - без проблем помещяются в боковое меню. 
    2. Пункт "Поддержать проект" - в диалог при нажатии на кнопку "информация".
    3. Пункт "Видеоплеер" - не понимаю почему?
    **Решение:** Вынести плеер в отдельное окно. А чтобы можно было быстро продолжить просмотр, явно добавить в то-же боковое меню пункт "продолжить просмотр".
    4. Информацию о версии клиента
    **Решение:** Перенести в пункт "информация" в боковом меню.
    5. Информация о залогиненом пользователе
    **Решение:** Аватарку юзера вынести в боковое меню первым пунктом. И там при нажатии в всплывающем окне отображать "выйти".
    И дополнительно при этом можно убрать статус авторизации внизу окна.

5. Поиск по названию релиза после всех вышеперечисленных изменений получается в неопределенном "состоянии", т.к. не очень понятно что с ним делать.
**Решение 1:** Перенести поиск вверх, чтобы он был доступен на всех экранах/фрагментах и искал только релизы.
**Решение 2:** Перенести поиск вверх, чтобы он был доступен только на тех экранах/фрагментах, на которых он нужен и искал в контексте открытого в данный момент экранах/фрагменте.
Немного сложно будет контролировать его, т.к. одно поле могут использовать все экраны.
Возможно стоит перенести его внутрь конкретных экранов, чтобы они точно имели свое поле поиска.

##### Что-же, с глобальным описанием закончили, теперь мелочевка
6. Такое чувство, что иконки из разных паков (либо из одного кривого), смотрится не гармонично. "Тонкие" и детализированные иконки рядом с толстыми.
**Решение:** Использовать иконки в одном стиле. Например тот-же MaterialDesign https://materialdesignicons.com/

7. Некоторые всплывающие окна не затеняют область за ними
**Решение:** Точно определиться когда нужно затенение, а когда нет и привести всё в соответствии с правилами.

8. В детальной о релизе, блок комментариев перекрывает всплывающие окна и их затенение. 
**Решение:** Сделать, чтобы блок комментариев не перекрывал всплывающие окна.

9. Календарь не имеет группировки по дням недели, отображается сплошным списком.
**Решение:** Сделать группировку по дням недели.

10. Когда нет данных, список пустой, отображается просто пустой экран.
**Решение:** Добавить заглушки с описанием почему нет данных.

##### Теперь субъективщина, UI и т.д.
11. Серый фон, еще более серая полоска сверху экрана, и на всём этом черный текст. Выглядит это как что-то из времён windows 95-98.
**Решение?:** Сделать гораздо более светлый фон, что-то прям в районе #f2f2f2.

12. Не знаю это тень или "border" у карточки релиза, но опять-же выглядит устаревшим.
**Решение?:** Сделать тень меньше по размеру более мягкой по цвету, либо вообще убрать.

13. Если будет выполнен пункт 1, то "быстрые действия" можно либо вообще убрать, или заменить на иконку "три точки" и перенести например в правый верхний угол карточки.

##### Что может получиться в итоге:
1. Пункты бокового меню: "войти/профиль", "синхронизация", "все релизы", "избранное", "уведомления", "календарь", "история", "просмотренные", "поиск", "случайный релиз", "youtube", "настройки", "информация".
    1. Пункт "войти/профиль" меняется в зависимости от состояния авторизации.
    2. Пункт "избранное" может быть скрыт, если пользователь не авторизован.
2. Плеер запускается в отдельном окне.
3. Все контекстные действия с карточками происходят в контекстном меню.
4. Все подпункты, относящиеся к конкретному экрану/фрагменту отображаются внутри экрана/фрагмента.
5. Нет лишней полоски с информацией внизу окна.
6. Дизайн более светлый, более чистый, с иконками в одной стилистике.
7. По клику в боковом меню открываются отдельные экраны, но само боковое меню доступно всегда.

В общем получается ± то-же самое по оформлению, но гораздо проще и понятнее, за счет привычных паттернов и за счет упрощения навигации. Так-же теперь никакого глобального состояния для одного списка релизов, все экраны и их данные "изолированы" друг от друга.

**Comment by trueromanus** [comment]
@RadiationX Спасибо за информативные и конструктивные предложения по улучшению приложения. Все проблемы услышаны, все идеи будут рассмотрены и возможно будут реализованы в следующих версиях.

Идея про плеер в отдельном окне уже есть тут #30 но до конца она пока не сформулирована.
