### ISSUE TITLE
Повышенное потребление gpu и cpu в режиме покоя

### ISSUE THREAD

**Issue by RadiationX** [anilibria/anilibria-winmaclinux#33]
Просто открываю приложение, ничего не делая, есть постоянная нагрузка, хотя в приложении ничего не происходит.
Есть предположение, что где-то происходит лишняя перерисовка интерфейса (т.к. есть нагрузка на gpu).

Версия приложения: 0.1.3 rc2
Постоянная нагрузка: ±4.5% cpu, 2-5% gpu.
Версия OS: MacOS 10.15.4
Железо: MacBook Pro 2015 15" (i7-4770hq, Intel Iris Pro 5200, 16gb ram, 2304 x 1440)

![image](https://user-images.githubusercontent.com/5782280/81604412-83b33400-93d8-11ea-90ea-870e994a923a.png)

**Comment by RadiationX** [comment]
На пк с windows так-же есть эта проблема, но проявляется немного иначе.
CPU вообще не нагружен, но есть постоянная нагрузка на GPU 0.5-1%. Если убрать "фокус" с окна, то нагрузка падает до 0%.

На макбуке нагрузка на cpu есть видимо из-за того, что видеоядро встроено в процессор.

Версия os на пк: Windows 10, build 1909
Железо пк: Ryzen 7 3700X, 32gb ram, nvidia rtx 2070s (8gb ram).

**Comment by trueromanus** [comment]
На Windows я уже нашел в чем было дело, оказывается для мигающего курсора на поле с фильтром по имени использовался gpu. Если с него снять фокус, а сейчас это невозможно без shortcut-а, то все в нули уходит. 
На macOS пока что я выяснил что проблема заключается в видеоплеере именно он потребляет какие-то ресурсы вероятно тонкости интеграции с quicktime.
