### ISSUE TITLE
Высокое потребление оперативной памяти

### ISSUE THREAD

**Issue by RadiationX** [anilibria/anilibria-winmaclinux#34]
Наблюдается высокое потребление оперативной памяти при скролле списка релизов. 
Без проблем (кроме дичайших лагов) удалось дойти до 7гб, дальше уже тяжело было, т.к. очень низкая отзывчивость приложения была.
Это не похоже не утечку памяти, скорее на кеширование битмапов всех постеров в оперативной памяти, т.к. после рефреша списка релизов потребление возвращается к "нормальным" 600мб.

Версия приложения: 0.1.3 rc2
Версия OS: MacOS 10.15.4
Железо: MacBook Pro 2015 15" (i7-4770hq, Intel Iris Pro 5200, 16gb ram, 2304 x 1440)
![image](https://user-images.githubusercontent.com/5782280/81610423-2cb25c80-93e2-11ea-8a48-cd0256026b8b.png)

**Comment by RadiationX** [comment]
Еще добавлю, что вместе с потреблением оперативной памяти, так-же повышается потребление CPU. Грузит ровно одно ядро на 100%. При этом наблюдаются жуткие фризы в приложении.
И это первое приложение, которое своей нагрузкой влияло на всю систему, т.к. остальные приложения тоже сильно тормозили.
Обычно даже полная нагрузка всей системы не приводит к каким-то сильными фризам.

**Comment by trueromanus** [comment]
Уменьшил немного по качеству изображения вроде не критично по внешнему виду но экономит лишний десяток мегабайт.
Добавил лимит на количество релизов в списке - не больше 80.
На самом деле очень странно что на маке аппетиты по памяти у qt в разы больше чем на других осях, пока не понятно почему.

По ссылке тестовый билд с вышеупомянутыми изменениями.
https://drive.google.com/file/d/1QKZVbhyJiKxZ5oXnV_pPvLcwOk-Cq7Qa/view?usp=sharing

**Comment by RadiationX** [comment]
Проверил тестовый билд - не похоже на решение проблемы, т.к. потребление в целом не изменилось. До 7гб дойти нельзя, но останавливается примерно на 1гб.
Возможно именно на макбуке такие цифры из-за того, что ram и vram объединены.

Еще проверил на пк с windows и ситуация похожа.
Там поведение немного другое, не получается довести до 7гб, приложение падает до этого.
Перед падением потребление ram ±1.4gb, video ram ±3gb.

Возможно, что всё-таки аппетиты везде примерно одинаковы, просто нужно еще мониторить потребление vram.

Версия os на пк: Windows 10, build 1909
Железо пк: Ryzen 7 3700X, 32gb ram, nvidia rtx 2070s (8gb ram).

**Comment by trueromanus** [comment]
Дак я же вроде и не написал что проблема решена:)
Память растет вместе со списком, виртуализация не поддерживается в стандартных контролах. Надо писать свой контрол а это не быстрое дело, поэтому пока для того чтобы исключить случаи фриза по всей системе я ограничил количество элементов в списке.

Я попробовал выгружать изображения когда они не области видимости но это помогает просто сократить до некоторой степени потребление памяти но не более того. Т.е. для полноценного решения проблемы нужен виртуализированный список в любом случае.

**Comment by RadiationX** [comment]
В тестовом билде обнаружил проблему с тем решением - похоже тот пункт про ограничение появляется в каждом списке при скролле до самого конца, независимо от того сколько фактически отображается элементов.

**Comment by trueromanus** [comment]
Спасибо, исправлено.

**Comment by trueromanus** [comment]
Решение проблемы перемещено в отдельную ишью #35
