### ISSUE TITLE
Невозможно собрать из AUR

### ISSUE THREAD

**Issue by CakesTwix** [anilibria/anilibria-winmaclinux#39]
![изображение](https://user-images.githubusercontent.com/57946485/84259705-8ad97900-ab21-11ea-8626-d0452efb6e45.png)
![изображение](https://user-images.githubusercontent.com/57946485/84259773-a2b0fd00-ab21-11ea-8a33-89c8fa1d5b0d.png)
![изображение](https://user-images.githubusercontent.com/57946485/84259836-b9efea80-ab21-11ea-8fa7-71906ac1b130.png)

**Comment by WaffleLapkin** [comment]
Ошибка воспроизводиться и простым `cd src && qmake && make`, так что проблема не в пакете.

**Comment by trueromanus** [comment]
https://github.com/anilibria/anilibria-winmaclinux/blob/426eceb9b6f1e3108099db6ab608b93ec527a88a/src/AniLibria.pro#L46

Попробуйте вставить это в строчку указанную выше.
```
QMAKE_CXXFLAGS += -lm
```

**Comment by trueromanus** [comment]
Исправлена проблема увеличения высоты текстового блока в поле поиска по имени релиза.

**Comment by trueromanus** [comment]
Скролбар сделаем, но это фича по этой баге я думаю стоит закрываться.
