### ISSUE TITLE
Не запускается после сборки из AUR (Arch Linux)

### ISSUE THREAD

**Issue by RazuvaevDD** [anilibria/anilibria-winmaclinux#40]
**Текущий результат:**
[user@localhost]$ AniLibria 
QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
QQmlApplicationEngine failed to load component
qrc:/main.qml:25:1: module "QtQuick.Dialogs" is not installed

**Ожидаемый результат:** 
Приложение запуститься

**Вероятные причины:** 
Нет необходимых зависимостей в пакете для компиляции и развертывания из AUR.

**Характеристики:**
OS: _Arch Linux_ 
Kernel: _x86_64 Linux 5.10.5-arch1-1_
Shell: _bash_
Resolution: _1920x1080_
WM: _Awesome_
GTK Theme: _Adwaita [GTK3]_

**Comment by WaffleLapkin** [comment]
Хм, я только что обновился (`local/anilibria-winmaclinux-git r230.e947749-1`), у меня запускается. Возможно у меня уже стоят нужные библиотеки :thinking:

**Comment by trueromanus** [comment]
Попробуйте установить пакеты qt5-quickcontrols и qt5-quickcontrols2

**Comment by RazuvaevDD** [comment]
Установка qt5-quickcontrols2 разрешила проблему, добавьте его в зависимости пожалуйста.

**Comment by WaffleLapkin** [comment]
Добавил
