### ISSUE TITLE
Exception after running app on Linux

### ISSUE THREAD

**Issue by borisgk98** [anilibria/anilibria-winmaclinux#44]
https://aur.archlinux.org/packages/anilibria-winmaclinux-git
I install package with `yay -S anilibria-winmaclinux-git`
After this i ran app and get exception:
```
QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
QQmlApplicationEngine failed to load component
qrc:/main.qml:25:1: module "QtQuick.Dialogs" is not installed
```
I fix it with `yay -S qt5-quickcontrols`
Please add this dependency to AUR package

**Comment by trueromanus** [comment]
Thank you for report issue. 
@WaffleLapkin Please add package qt5-quickcontrols in dependencies.

**Comment by WaffleLapkin** [comment]
I added the missing dependency, so everything should be fine again :)

P.S. @trueromanus you've misspelt "package" in `aur` label description.

**Comment by trueromanus** [comment]
> P.S. @trueromanus you've misspelt "package" in `aur` label description.
Fixed, thanks for your vigilance 👌
