### ISSUE TITLE
Cannot open downloaded torrent files automatically

### ISSUE THREAD

**Issue by uunnxx** [anilibria/anilibria-winmaclinux#45]
### It rarely works as expected...
Sometimes it will download `*.torrent` files as __an empty__ file, and I'm not able to open it manually. (I can only reinstall the program a few times to get it work.) 
 
> Now, it's working in this step:
>  - Select ___download an Anime___
>  - __It will download it__ _( if it fails it will download an empty `*.torrent` file and I should reinstall an app to get it work )_
>  - Manually run `xdg-open ~/.local/share/EmptyFlow/AnilibriaDesktopClient/*.torrent` 

- `Distributive: Ubuntu 20.10 groovy | Linux host 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- `App install method: AppImage`

Log:
```
Cache location:  "/home/USER/.local/share/EmptyFlow/AnilibriaDesktopClient"
/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner: symbol lookup error: /usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner: undefined symbol: _gst_executable_path

(AniLibria:1770855): GStreamer-WARNING **: 07:28:22.625: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
No WebView plug-in found!
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
/usr/bin/transmission-gtk: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
/usr/bin/transmission-gtk: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)
/usr/bin/transmission-gtk: symbol lookup error: /usr/bin/transmission-gtk: undefined symbol: gtk_menu_popup_at_pointer
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
/usr/bin/perl: /tmp/.mount_anilib8UuOMX/lib/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /usr/bin/perl)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_anilib8UuOMX/lib/libselinux.so.1: no version information available (required by sed)
/usr/bin/xdg-open: 869: google-chrome-stable: not found
/usr/bin/xdg-open: 869: google-chrome-stable: not found
xdg-open: no method available for opening 'file:///home/USER/.local/share/EmptyFlow/AnilibriaDesktopClient/e5e7ed952d574dc58bb315ce932c0c82.torrent'
```

**Comment by trueromanus** [comment]
Can you please reveal some information?
- Linux distributive
- How you installed the application? (AppImage, deb, build from source)

**Comment by uunnxx** [comment]
I'm sorry, forgot about it... updated

**Comment by uunnxx** [comment]
Now, I installed `deb` version, and it's working as expected.

Dependency for `deb` version: `libqt5websockets5-dev`

**Comment by trueromanus** [comment]
I redeployed deb file that contains libqt5websockets5-dev dependency. Can you please check it out?

**Comment by uunnxx** [comment]
Yes, it asks for `libqt5websockets5-dev`

![anilibria1](https://user-images.githubusercontent.com/6236057/115535884-d7ddbe00-a2a1-11eb-84fe-878fe6010f2c.png)


![anilibria2](https://user-images.githubusercontent.com/6236057/115535898-dad8ae80-a2a1-11eb-8e8b-2b84158785d6.png)

**Comment by trueromanus** [comment]
> Yes, it asks for `libqt5websockets5-dev`
> And I can install it via `apt install -f`
  
As I understand it normal way install it.  

> When dpkg installs a package and a package dependency is not satisfied, it leaves the package in an "unconfigured" state and that package is considered broken.
> 
> The sudo apt-get install -f command tries to fix this broken package by installing the missing dependency.
> 
>

**Comment by uunnxx** [comment]
I think so, thank you
