### ISSUE TITLE
Скролл настроек при маленьком размере окна

### ISSUE THREAD

**Issue by Asethon** [anilibria/anilibria-winmaclinux#46]
Сразу скажу: сижу я на линуксе(Kubuntu 20.04), для общего понимания.
Ситуация следующая:
![image](https://user-images.githubusercontent.com/34743506/118317207-6be92100-b500-11eb-8585-cd2dba2bbf08.png)

Настройки не полностью влезают в окно и их нельзя проскроллить. Единственный выход - увеличить окно, чтобы все пункты попадали в него.

**Comment by trueromanus** [comment]
Исправлено.
Войдет в версию:
сборка из исходников - уже вошло
бинарная сборка - войдет в 1.0.2
