### ISSUE TITLE
qt5-default and dependencies based on qt

### ISSUE THREAD

**Issue by uunnxx** [anilibria/anilibria-winmaclinux#47]
Since `qt5-default` was removed from `Ubuntu 21.04` with changelog:
> Remove qt5-default. Nowadays it's not needed as Qt 5 is the only Qt version in Debian and it brought more problems than solutions.

We have dependencies from `qt5-default` which we cannot be able to install it even by downloading it, `https://packages.ubuntu.com/groovy/amd64/qt5-default/download` because it's depends on other tools...

I'm asking what we can do ?

`Links:`
https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04

**Comment by trueromanus** [comment]
Hello and thank you for request.
I republish package without qt5-default dependency.
Please check it out.

**Comment by uunnxx** [comment]
Thank you, now it works! <3
