### ISSUE TITLE
[Linux] Failed to load plugin

### ISSUE THREAD

**Issue by Demetri0** [anilibria/anilibria-winmaclinux#5]
Приветствую, решил чисто из интереса попробовать запустить у себя на linux, GUI запустился, но контент отсутствует.

[Лог](https://github.com/anilibria/anilibria-winmaclinux/files/4365420/anilibria.log)

`gstreamer` у меня установлен версии `1.0`. Мне кажется перечисленные в логе плагины, нужно паковать вместе с самим приложением.

Кроме того что-то не так с OpenSSL, не знаю почему она `Incompatible` у меня в системе стоит версия `1.1.1c-1ubuntu4`

![Ну и скриншотик если интересно](https://user-images.githubusercontent.com/6806547/77252409-e102f280-6c7d-11ea-97d4-b7cee1a44535.png)

**Comment by trueromanus** [comment]
Спасибо за интерес к проекту!

Сразу скажу что для linux это мой первый проект так что я могу все делать не верно.
Gstreamer не включен в пакет потому что у меня не получилось пока его туда включить, если включить то приложение вообще не стартует. Насчет openssl на той версии Qt что я собирал юзается 1.0 и он не принимает другие версии :(. Поидее надо пересобирать на старшей версии которая уже юзает 1.1. 

И да, если вдруг  появиться желание помочь сборкой или хотя бы советом то welcome😁

**Comment by trueromanus** [comment]
Можете попробовать эту версию, я закинул в нее весь gstreamer.

https://drive.google.com/file/d/1vu48Meu_Tr8nns5PHqZrk3dKqpYbqrgR/view?usp=sharing

**Comment by trueromanus** [comment]
А насчет ssl можно попробовать установить пакет libssl1.0-dev

**Comment by Demetri0** [comment]
> А насчет ssl можно попробовать установить пакет libssl1.0-dev

Его уже нету в оффициаьном репозитории, только слева откуда-нибудь искать. Кроме того хотелось бы чтобы оно запускалось из коробки, как мне кажется appimage именно для этого и задумывался.

Когда я собирал свою приложеньку под винду мне туда помниться приходилось пихать библиотечку для ssl (Qt5Sql.dll рядом с exe-шником), я уже ничерта не помню если честно. В распакованном appimage я не нашёл такой, попробуй посмотреть может как-то можно её туда запаковать, чем чёрт не шутит.

А на счёт gstreamer сообщения не исчезли, но вроде это просто warning-и пока что думаю можно забить.

**Comment by trueromanus** [comment]
> Его уже нету в оффициаьном репозитории, только слева откуда-нибудь искать. Кроме того хотелось бы чтобы оно запускалось из коробки, как мне кажется appimage именно для этого и задумывался.
> 
Собрал правильную версию openssl 
и включил в сборку, правда так и не смог проверить грузит ли он ее при запуске. Новая линка - https://drive.google.com/file/d/1HIZCgtPjnftcO19hawOE5g60UcG7xw35/view?usp=sharing
 
> А на счёт gstreamer сообщения не исчезли, но вроде это просто warning-и пока что думаю можно забыть.  

Я думаю что эти сообщения намекают что внутренний плеер в приложении не будет работать. Я копался и понял что сканер для gstreamer-а по умолчанию берется из системы и чтобы оно завелось из appimage надо добавлять переменные окружения для gstreamer-а, правда на чистой системе так и не удалось это завести.  
> p/s: у меня нет цели добиться запуска у себя, я хочу приложение запускалось у любого кто скачает appimage

У меня такая же цель 😉. Я просто накидывал варианты.

**Comment by Demetri0** [comment]
Да, проблема с SSL действительно решена, и да видео не воспроизводится, я наткнуся на вот этот комментарий, похоже человек смог-таки заставить его работать

https://github.com/probonopd/linuxdeployqt/issues/123#issuecomment-346934117

+ там же, чуть ниже - похоже можно подглядеть переменные окружения +/- рабочие на всех дистрибутивах, если я правильно понял
https://github.com/probonopd/linuxdeployqt/issues/123#issuecomment-346935456

И тут же ниже человек отписывается про проблему с тем что AppRun это просто симлинк, на что ему ответили что впринципе можно просто заменить его непосредственно бинарником
https://github.com/probonopd/linuxdeployqt/issues/123#issuecomment-392000629

Надеюсь что это чем-нибудь поможет, удачи :)

**Comment by trueromanus** [comment]
Вроде все затолкал, переменные окружения подфигачил, у меня на чистой системе завелся gstreamer правда все равно какие варнинги выдал.
Новая линка -
https://drive.google.com/file/d/10JYQGL2HjUZA6uthgfj2jJsrxEs_Jy1T/view?usp=sharing

**Comment by Demetri0** [comment]
Да, похоже всё и правда отлично работает.
Единственное что ещё хотелось бы уточнить:
`Cache location:  "/home/d3i0/.local/share/EmptyFlow/AnilibriaDesktopClient"`

не лучше ли для кеша использовать `QStandardPaths::CacheLocation` ?

**Comment by trueromanus** [comment]
На самом деле это я так просто называю эти данные:). Эти данные должны жить ~~вечно~~долго и их там много. А как раз cachelocation это папка которую могут удалить в любой момент и это никоим образом не должно отразиться на работе программы. То в случае этой программы пользователю нужно будет снова выкачать кеш релизов, авторизоваться что не совсем ожидаемое поведение.

**Comment by Demetri0** [comment]
Понятно. Ну тогда благодарю за быстрый фидбэк и доведение программы до работоспособности. Если ещё будут вопросы буду писать :)
