### ISSUE TITLE
Неочевидная работа с избранным

### ISSUE THREAD

**Issue by rostislavYurievich** [anilibria/anilibria-winmaclinux#52]
Кажется неочевидным что в кинозал зайти с бокового меню можно, а в избранное нельзя (хотя вроде бы по сообщению "избранное недоступно" подразумевается что можно).
Из списка релизов избранное по прежнему доступно.
Не уверен баг это или фича, но в первое время не понимал в чем проблема и почему нельзя зайти в избранное.

**Comment by trueromanus** [comment]
![image](https://user-images.githubusercontent.com/9040186/129264459-154333a6-7b66-435b-9430-b6f7440f7df3.png)
Выше списка находятся основные фильтры для релизов, избранное один из них. Он второй слева в виде звезды.
В боковом меню в основном находятся действия типа добавить или удалить и т.п. Чтобы меню избранное стало активным надо выбрать релизы в списке.

**Comment by rostislavYurievich** [comment]
Может стоит добавить информацию об этом в это сообщение?
![Screenshot_20210813_120224](https://user-images.githubusercontent.com/88634406/129333537-800d7851-3da6-499f-bcee-9b273c9e8b30.png)

**Comment by trueromanus** [comment]
Добавил уточнение про избранное в этом диалоге.
