### ISSUE TITLE
Неочевидная работа переключения серии в плеере

### ISSUE THREAD

**Issue by rostislavYurievich** [anilibria/anilibria-winmaclinux#53]
Список серий в левой части экрана расположен по возрастанию, сверху вниз.
Однако при этом PgUp и PgDn включают следующую и предыдущую серию. Очевидней было бы обратное поведение.

Кроме этого использование таких горячих клавиш может быть затруднительно на неполных клавиатурах. Предлагаю добавить дополнительные хоткеи N(от Next) и P (от Previous) для следующего и предыдущего трека в списке.
Хоткей отвечающий за переключение режима "поверх всех окон" можно переназначить на T (от always on Top).

Так как узнать о том какие клавиши довольно затруднительно, хорошо было бы добавить инфу о хоткеях в тултипы.

**Comment by rostislavYurievich** [comment]
Добавил решение в pull request.

Кстати хоткей включающий предыдущее видео вызывал что-то странное и до этого не работал.

**Comment by rostislavYurievich** [comment]
Не пойму как прикрепить pull request сюда честно говоря, так бы сделал

**Comment by trueromanus** [comment]
> Так как узнать о том какие клавиши довольно затруднительно, хорошо было бы добавить инфу о хоткеях в тултипы.

У приложения есть канал в телеге где есть информация обо всех shotcut-ах. Да возможно не удобно, но с другой стороны подсказки читают тоже не сказать чтобы очень много людей :). Заведу чуть позже для остальных тоже в подсказках.
