### ISSUE TITLE
Неправильно указаны категории Desktop Entry

### ISSUE THREAD

**Issue by rostislavYurievich** [anilibria/anilibria-winmaclinux#55]
В спецификации категории "Application" и "Multimedia" не представлены, поэтому их стоит заменить для корректной работы. Также можно добавить категорию Qt 

Спецификация:
https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by trueromanus** [comment]
Можно было и не создавать ишью а просто указать это в PR :) и там тоже есть обсуждения если что надо было обсудить.
