### ISSUE TITLE
После открытия "Полезных ссылок" не работает скролл

### ISSUE THREAD

**Issue by rostislavYurievich** [anilibria/anilibria-winmaclinux#57]
1. Открыть список полезных ссылок
2. Нажать на фон появившегося окошка
Теперь скролл релизов колесиком мыши не работает

**Comment by rostislavYurievich** [comment]
Обманул, так умеют все модальные окна бокового меню

**Comment by rostislavYurievich** [comment]
Воруют фокус если я правильно понимаю

**Comment by trueromanus** [comment]
Не удалось повторить поэтому нужны знать на какой ОС, какое окружение и т.п.

**Comment by rostislavYurievich** [comment]
debian kde, иногда несколько раз тыкнуть надо, но воспроизводится стабильно

**Comment by trueromanus** [comment]
После "Нажать на фон появившегося окошка" чтобы Вы нажимаете или делаете?

**Comment by trueromanus** [comment]
Закрыто из-за того что не удалось воспроизвести. Если проблема все еще актуальна переоткройте ишью и дополните большей информацией, очень хотелось бы увидеть видео с проблемой. Спасибо!
