### ISSUE TITLE
Build error on Arch Linux

### ISSUE THREAD

**Issue by WaffleLapkin** [anilibria/anilibria-winmaclinux#61]
Installing the app on Arch Linux fails with a [huge error](https://gist.github.com/WaffleLapkin/ca58f820954b9ded85c30f9c5cac51a4).

## To Reproduce

Try installing or updating the app via an AUR helper, for example `yay`:
```
; yay -S anilibria-winmaclinux-git
```

**Comment by trueromanus** [comment]
Hello and thanks for you request.
I commit changes. Please check it out.

**Comment by trueromanus** [comment]
I check it and I think it fixed but if not feel free reopened this issue. Thanks

**Comment by WaffleLapkin** [comment]
It works, thanks!
