### ISSUE TITLE
нет иконки приложения в dash-to-panel

### ISSUE THREAD

**Issue by kodirovshchik** [anilibria/anilibria-winmaclinux#63]
**Describe the bug**
Ubuntu 21.04 нет иконки приложения в dash-to-panel. Вместо иконки приложения используется дефолтный значок используется дефолтный.

**To Reproduce**
1. Запустить приложение AniLibrix-linux-arm64-1.4.0.AppImage, на Ubuntu 21.04, с расширением dash-to-panel v42.

**Expected behavior**
Ожидалось наличие иконки приложения приложения в dash-to-panel.

**Screenshots**
https://imgur.com/YNPf0xQ
https://imgur.com/YQmSL6C

**Additional context**
При этом в трее (gnome-shell-extension-appindicator) значок у приложения свой собственный, а не дефолтный.

**Comment by trueromanus** [comment]
Здравствуйте, Вы ошиблись репозиторием, Вам сюда https://github.com/pavloniym/anilibrix.
