### ISSUE TITLE
Зеленый экран при воспроизведении видео

### ISSUE THREAD

**Issue by CaptainQuake** [anilibria/anilibria-winmaclinux#65]
После недавнего обновления mpv который вышел примерно 5-7 дней назад, при воспроизведении видео в программе Abilibria версии 1.0.4 появляется зеленый экран вместо видео, а звук идет.
Все прочие видео на ПК за исключением тех, что в программе Abilibria, воспроизводятся без каких либо проблем.

OS: Arch Linux
Ставил программу через AUR

![Screen_20211105-223346](https://user-images.githubusercontent.com/75237891/140569569-ea9392ff-e711-42d2-a816-aea344420c76.png)

**Comment by CaptainQuake** [comment]
В версии [Anilibrix](https://github.com/pavloniym/anilibrix/) видео воспроизводится без проблем
![Screen_20211105-233340](https://user-images.githubusercontent.com/75237891/140575261-09698ee7-6f14-474a-b194-b59445982d4a.png)

**Comment by trueromanus** [comment]
Здравствуйте, запустите из консоли, откройте воспроизведение видео и скиньте сюда лог. Я думаю там будет подсказка что идет не так.

**Comment by CaptainQuake** [comment]
> Здравствуйте, запустите из консоли, откройте воспроизведение видео и скиньте сюда лог. Я думаю там будет подсказка что идет не так.

К сожалению, никакой полезной информации не выдало. При запуске лишь показал путь к папке кеша и всё. Воспроизводил несколько видео и никакой реакции в терминале.
![Screen_20211106-214317](https://user-images.githubusercontent.com/75237891/140620520-f5e87118-e011-41cd-b7f7-3949d7930ac8.png)

**Comment by trueromanus** [comment]
Тогда вот план действий
Попробуйте на другом качестве если не поможет как вариант можно попробовать пересобрать через aur еще раз может подтянет новые локальные зависимости.

**Comment by CaptainQuake** [comment]
> Тогда вот план действий Попробуйте на другом качестве если не поможет как вариант можно попробовать пересобрать через aur еще раз может подтянет новые локальные зависимости.

Пробовал менять качество, все кеши программы тоже чистил. Даже перебрал файл настроек mpv. Именно те параметры которые отвечают за аппаратное ускорение и декодирование. 
![Screen_20211106-215446](https://user-images.githubusercontent.com/75237891/140620810-67700224-3614-4026-a427-5f845814a101.png)


Потом вернул все как было. Сейчас попробую пересобрать, хотя сомневаюсь, что это поможет.
P.S. У меня все работало до того момента, пока не прилетела обнова mpv

**Comment by CaptainQuake** [comment]
Сделал пересборку. Как и ожидалось, результата нет. Буду копать дальше.

**Comment by trueromanus** [comment]
Ишью было закрыто из-за большого периода бездействия. Если проблема актуальна пожалуйста переоткройте это ишью.
