### ISSUE TITLE
Пожелания для улучшений/изменений

### ISSUE THREAD

**Issue by CaptainQuake** [anilibria/anilibria-winmaclinux#67]
В общем, за долгое время использования программы у меня накопились кое какие пожелания для улучшений и изменений. Решил о них написать в надежде, что эти возможности реализуют.

***
1. Возможность добавить в "Избранное" даже если нет регистрации. Данные о таких закладках будут храниться локально.
***
2. Функция буферизации. В программе очень маленькая буферизация. Бывают ситуации, когда низкая скорость интернета и смотреть аниме с тормозами каждые 5-10 секунд очень тяжко. При увеличении буферизации можно будет поставить видео на паузу и оставить на некоторое время, чтобы оно прогрузилось. Сделайте данную функцию как опцию в настройках, чтобы пользователь сам выбирал уровень буферизации.
***
3. Допустим, видео немного загрузилось и я начал смотреть. Если я нажму на паузу, буферизация тоже прекращается. Оно начинает работать только если нажать на Play. Ни в одном плеере такого не встречал. Должно быть наоборот, при паузе прогрузить определенное кол-во данных, чтобы при нажатии на Play прогруженное видео воспроизводилось сразу. 
***
4. Очень сильна нужна кнопка закрыть плеер. Не понимаю, почему ее до сих пор нет. Чтобы закрыть серию, обязательно надо переходить в какое либо меню и искать в списке аниме которое только что смотрел. Нужно чтобы при нажатии на закрыть, программа переходила к базовой странице с аниме, где есть постер, описание, комментарии.  
![3](https://i.imgur.com/n54p7O7.png)
***
5. Все мониторы уже очень давно широкие. По высоте места всегда мало, а по бокам места всегда хватает. Нужна возможность переместить комментарии влево или вправо. Внизу читать их крайне неудобно.  Сделайте данную возможность как опцию в настройках. Каждый сделает как ему удобнее. Главное чтобы размер окошка с комментариями был не слишком большим. Для примера сделал комментарии побольше, чтобы было нагляднее, но не обязательно их так растягивать как на скрине.
![1](https://i.imgur.com/sTzCtVX.png)
![2](https://i.imgur.com/apoX1RP.png)
***
6. Убирать рамки при клике на видео. Порой смотришь видео, задел мышку или еще что, появляются рамки и в этом нет ничего такого, за исключением одного момента. Надо отвести мышь за рамку и ждать, пока эти рамки не исчезнут. Во многих плеерах они убираются и появляются при клике на само видео.
![4](https://i.imgur.com/s2mqqBE.png)
***
7. Нужна возможность копировать описание и имя
***

**Comment by trueromanus** [comment]
Здравствуйте, спасибо за обращение.
1 Внесено в список на будущее
2 и 3 пункты. Буфферизация в программе достаточная и равна 3 минутам. "Бывают ситуации, когда низкая скорость интернета и смотреть аниме с тормозами каждые 5-10 секунд очень тяжко" боюсь что буферизация к этому не имеет никакого отношения потому что если какой-то фрагмент не удается скачать по причине плохой связи плеер пытается сделать это с самого начала. На паузу нет буферизации потому что по каким-то сакральным причинам в desktop плеерах такой функции либо нет совсем либо на паузу просто докачивается текущий фрагмент который уже начал качаться. Я пробовал несколько разных плееров и тот что сейчас есть самый нормальный из них :(
4 Кнопка закрыть есть и их целых две (левая кнопка в тулбаре окна и кнопка меню внизу справа в контрольной панели), еще и клавишу Esc можно нажать. Тут я вижу проблема не в отсутствии кнопки, а в том что Вы хотите чтобы оставалась открытой карточка релиза если она была открыта до этого. Не знаю зачем Вам это но добавим на это настройку.
5 Все мониторы уже очень давно действительно широкие, но не обязательно большие :) например на среднестатистическом ноуте. К сожалению компоновка карточки очень странная из-за комментариев в большинстве своем. Вообщем надо подумать что с этим можно сделать.
6 Внесено в список на будущее
7 Это можно сделать тут 
![image](https://user-images.githubusercontent.com/9040186/144573436-0033bd35-06f8-4a2a-9673-561e0dcb91ee.png)

**Comment by trueromanus** [comment]
"Почему-то у меня даже близко такого нет. Специально пытаюсь прогрузить побольше. " - окей замерил одна минута двадцать секунд плюс минус буфер видео.
"Если буферизация не работает на паузе, то в ней особо смысла инет. В том плане, что нет смысла ставить ее на 3 минуты. Даже 1-й минуты хватит с лихвой. Все у кого небольшая скорость, в плане буферизации в пролете, а те у кого хорошая скорость, высокая буферизация и не нужна." - ну вообще буферизацию придумали чтобы смотреть видео подгружая его частично во время этого процесса (процесса воспроизведения) держа в памяти только ограниченный буфер видео фрагментов. Даже если будет буферизация на паузе ну ок я подгрузил следующие 5 минут видео в память, нажал воспроизведение, посмотрел 5 минут и снова встал на ожидание следующих 5 минут потому что интернет слабый. Всю серию не видел чтобы плееры на паузе буферизировали. Если скорость инета низкая проще скачать с торента целое видео и не мучаться.
"Я нажимал во время воспроизведения на все кнопки, что есть в программе. Ни одна из них не закрывает воспроизведение так, как я описывал выше. Esc возвращает к каталогу релизов, а не к описанию аниме которое я смотрю. Все остальные варианты перекидывают в различные разделы. Можете заскринить эти кнопки, которые Вы имеете ввиду?
Объясню нагляднее на скринах, что имел ввиду я.
Допустим, я смотрю аниме Меня выгнали из отряда героя, поэтому я решил спокойно жить в глуши
а затем как на скрине" - я прекрасно понял проблему, но как я сказал выше решать ее добавлением еще одной кнопки смысла нет, ниже те самые кнопки которые выполняют переход к странице каталог релизов.
![image](https://user-images.githubusercontent.com/9040186/144646780-51071153-a05b-44b1-8ea6-fba3f72485a5.png)
Когда Вы переходите со страницы каталог релизов на страницу видеоплеера открытая карточка релиза (это область где подробная инфа о релизе плюс коментарии) автоматически закрывается. Добавлю настройку при включении которой она не будет закрывать карточку релиза и как следствие переход к странице каталога релизов произойдет с открытой карточкой релиза.

**Comment by CaptainQuake** [comment]
Понятно. В любом случае, буду ждать изменений)

**Comment by trueromanus** [comment]
Загрузку на паузе не будет :(. В плеере такой фичи из коробки нет а делать ее патчами на плеер долго и ресурсозатратно.
Вынес локальное избранное в отдельную ишью #68. Будет в следующих релизах.
В релиз 1.1.1 вошло:
- Комментарии можно вытащить в отдельное окно и крутить вертеть ими как необходимо (https://t.me/desktopclientanilibria/198). После закрытия карточки релиза или переходов окно не остается.
- Добавлена настройка для того чтобы осталась карточки релиза открытой (https://t.me/desktopclientanilibria/196) после возврата любым способом на страницу Каталог релизов.
- Клик на области видео скрывает органы управления (https://t.me/desktopclientanilibria/195)

Эту ишью закрываю. Если будет еще что-то желательно писать по одной ишью на одну проблему потому что отслеживать обсуждение по одной конкретной проблеме для списка сложнее.

**Comment by CaptainQuake** [comment]
> Загрузку на паузе не будет :(. В плеере такой фичи из коробки нет а делать ее патчами на плеер долго и ресурсозатратно. Вынес локальное избранное в отдельную ишью #68. Будет в следующих релизах. В релиз 1.1.1 вошло:
> 
>     * Комментарии можно вытащить в отдельное окно и крутить вертеть ими как необходимо (https://t.me/desktopclientanilibria/198). После закрытия карточки релиза или переходов окно остается.
> 
>     * Добавлена настройка для того чтобы осталась карточки релиза открытой (https://t.me/desktopclientanilibria/196) после возврата любым способом на страницу Каталог релизов.
> 
>     * Клик на области видео скрывает органы управления
> 
>     * Клик на постер в видеоплеере позволяет перейти к карточке релиза сразу (https://t.me/desktopclientanilibria/195).
> 
> 
> Эту ишью закрываю. Если будет еще что-то желательно писать по одной ишью на одну проблему потому что отслеживать обсуждение по одной конкретной проблеме для списка сложнее.

Спасибо за проделанную работу!
