### ISSUE TITLE
Клик в панель уведомлений происходит сквозь эту панель и открывает селектор сортировки

### ISSUE THREAD

**Issue by MrDreek** [anilibria/anilibria-winmaclinux#69]
**Describe the bug**
Клик в панель уведомлений происходит сквозь эту панель и открывает селектор сортировки

**To Reproduce**
1. На главном экране нажать на иконку колокольчика
2. Кликнуть чуть ниже кнопки "Очистить все"
3. Увидеть, что открылся селектор выбора сортировки

**Expected behavior**
Не должно быть кликов сквозь панель уведомлений

**Screenshots**
![image](https://user-images.githubusercontent.com/11575687/145591976-5b9a1da4-55f3-4c85-97d5-5cfa2d55a667.png)

**Device**
 - Type: Компьютер
 - OS: windows 10
 - Version: 1.1.1
 - Разрешение экрана FullHD при 100% скейлинге в настойках Windows

**Additional context**
Баг никак не влияет на функциональность, лишь забавное поведение, так что очень низкий приоритет

**Comment by trueromanus** [comment]
Исправлено и войдет в версию 1.1.2.
