### ISSUE TITLE
чем собирать?

### ISSUE THREAD

**Issue by KnightMurloc** [anilibria/anilibria-winmaclinux#7]
решил собрать из исходников для linux но нигде не нашёл информации ни про зависимости ни про систему сборики и компилятор. может добавите эту информацию?

**Comment by trueromanus** [comment]
Не ожидал что уже кто-то решиться на сборку из исходников:)

Как думаете стоит ли добавлять также информацию о том как установить зависимоти в систему через пакетный менеджер?

**Comment by KnightMurloc** [comment]
> Как думаете стоит ли добавлять также информацию о том как установить зависимоти в систему через пакетный менеджер?
это слишком дистрибутиво зависимая часть. думаю не стоит.

**Comment by WaffleLapkin** [comment]
А мне кажется что имеет смысл добавить и инструкции для разных дистрибутивов. (можно спрятать под спойлер чтобы много места не занимало и было просто найти свой дистр)

**Comment by trueromanus** [comment]
Обновил readme.
Добавил компиляторы, и зависимости для linux.
Инструкции для дистров будем добавлять постепенно, если есть желание помочь то welcome :)

**Comment by WaffleLapkin** [comment]
Хм, у меня инструкция из README не работает, `qmake` просто выводит помощь:
```console
% qmake
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project
...
```

**Comment by KnightMurloc** [comment]
> Хм, у меня инструкция из README не работает, `qmake` просто выводит помощь:
> 
> ```
> % qmake
> Usage: qmake [mode] [options] [files]
> 
> QMake has two modes, one mode for generating project files based on
> some heuristics, and the other for generating makefiles. Normally you
> shouldn't need to specify a mode, as makefile generation is the default
> mode for qmake, but you may use this to test qmake on an existing project
> ...
> ```
Это нужно выполнить в папке src

**Comment by trueromanus** [comment]
Обновил readme, добавил команду переходу в папку src на всякий

**Comment by trueromanus** [comment]
@KnightMurloc если достаточно информации закрой ишью
