### ISSUE TITLE
segmentation fault при закрытии приложения.

### ISSUE THREAD

**Issue by KnightMurloc** [anilibria/anilibria-winmaclinux#79]
segmentation fault при закрытии приложения.

версия из aur. поведение прослеживается как на git версии так и на стабильной.

 - OS: Manjaro Linux

**Comment by trueromanus** [comment]
Ошибка в libQt5Multimedia. Судя по багтрекеру Qt ошибка пофикшена, но в только в коммерческой версии. В общем будем ждать когда пофиксят в версии 5.15.2, думаю что смысла делать fallback на 5.13 нет смысла потому что ошибка не критическая и на функционал завершения не влияет.
