### ISSUE TITLE
Сборка anilibria-winmaclinux для AltLinux

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#81]
Привет.
Я скомпилировал anilibria-winmaclinux для дистрибутива AltLinux, если вы не возражаете, добавьте пожалуйста в описание README.md, что:

AltLinux
Установка пакета anilibria-winmaclinux из репозитория используя консоль:
$ su - -c 'apt-get install anilibria-winmaclinux'
или через любой графический менеджер пакетов.

Заранее спасибо :-)

**Comment by trueromanus** [comment]
Здравствуйте, благодарю за участие в развитии проекта.

Я бы рекомендовал Вам сделать PR в проект. Таким образом Ваша контрибуция будет зафиксирована, Вы как автор будете присутствовать в списке контрибуторов на главной странице репозитория. Также Вы останетесь в истории проекта. Если не знаете как это сделать я могу подсказать куда и что.

**Comment by Koi-foo** [comment]
Отправил изменения, надеюсь все сделал правильно).
