### ISSUE TITLE
Добавление anilibria-winmaclinux в репозитории роса линукс

### ISSUE THREAD

**Issue by X1mper** [anilibria/anilibria-winmaclinux#83]
Добавили собранную мной программу в репозитории
Писал об этом в http://anilibriadesktop.reformal.ru/proj/?ia=1209630
Я с гитхабом не знаком, так что жду разъяснений действий (что делать и как)

**Comment by trueromanus** [comment]
Здравствуйте, чтобы создать PR необходимо вначале создать форк по ссылке https://github.com/anilibria/anilibria-winmaclinux/fork 
Далее произвести обновление файла README.md.
Добавьте метод для установки Вашего пакета из репозиториев в секции **Пакеты для пакетных менеджеров Linux**.
Примеры как это может выглядеть можно посмотреть [здесь](https://github.com/anilibria/anilibria-winmaclinux#arch-linux)
После чего необходимо закомитить изменения в вашем форке и сделать Pull Request. Инструкцию как сделать Pull Request можно изучить [тут](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by X1mper** [comment]
Правильно ли я все сделал?

**Comment by trueromanus** [comment]
Да все правильно, спасибо за участие в проекте!
