### ISSUE TITLE
Автопропуск оппенинга

### ISSUE THREAD

**Issue by niallipa** [anilibria/anilibria-winmaclinux#86]
Кнопку сделали, но хочу рычажок, если включен - автонажатие этой кнопки, лень подходить к компу чтобы ее нажать ее и скипнуть. Так же если в будущем появится кнопка скипа эндинга (вдруг в конце серии будет после эндинга что-то), то и для автонажатие кнопки эндинга рычажок. + на экране где-то где эта кнопка сделать надпись на пару секунду, что произошел автоскип оппенинга (как например это реализовано на ютубе в модуле спонсор блок)

**Comment by trueromanus** [comment]
Добавлена настройка "Автопропуск опенинга" на странице "Видеоплеер". Изменение войдет в версию 1.1.12.
