### ISSUE TITLE
Дизайн и функционал

### ISSUE THREAD

**Issue by Dezexus** [anilibria/anilibria-winmaclinux#88]
Интерфейс
1 Страница релиза
1) Название релиза, альтернативное название нет надобности +- одного размера с основным, так как для большинства пользователей оно не является важным.
 
![image](https://user-images.githubusercontent.com/61343836/194067692-43e412df-d0f4-49d2-9008-102ca62f0df4.png)

2) Количество торрентов не несёт какой-либо полезной информации, а потому за его счёт, можно увеличить кнопку скачивания под ширину постера и добиться симметричного более приятного на вид и упростить к ней доступ.
 
![image](https://user-images.githubusercontent.com/61343836/194067779-211c94ad-85eb-4c6d-8aba-490e022f516b.png)

3) Список серий
  3.1) С появлением отдельной панели с сериями в нижней части страницы потребность в кнопки с выпадающим списком серий отпала, так как она лишь дублирует имеющийся функционал.
  3.2) Так как превью серий генерируются не из начала видео как в большинстве плееров, а в случайном месте видео возникает возможность словить спойлер в момент выбора серии, по этому для компактности списка серий и избежания выше описанного случая, предлагаю использовать стандартный список серий.
 
![image](https://user-images.githubusercontent.com/61343836/194067812-4e23f162-b91e-4e2b-81d8-80d8756d8e15.png)

C возможностью запускать видеопоток с нужным качеством.

4) Полный вид страницы релиза
  
![image](https://user-images.githubusercontent.com/61343836/194067845-1be21d5b-69e5-4c11-83dc-b34757c6991c.png)

2. Страница расписания 
1) Страница расписания, в текущем виде, данная страница не пригодна для использования, так как релизы просто отсортированы, но никак не разделены, для исправления данной проблемы предлагаю добавить разделители с подписью дня недели.
 
![image](https://user-images.githubusercontent.com/61343836/194067874-4a1acac7-597d-4741-9d87-ef37b5a3610e.png)

2) Чтобы с экономить место и увеличить зону поиска предлагаю воспользоваться пустым пространством в шапке страницы и разместить там поиск, а процесс синхронизации отображать путём вращения значка синхронизации на навигационной панели. Также хотелось бы иметь возможность выделять текст в поисковой строке.
 
![image](https://user-images.githubusercontent.com/61343836/194067914-001023e4-904e-4dff-bb2e-7b11a88b7c24.png)

3. Страница плеера
 
 До
![image](https://user-images.githubusercontent.com/61343836/194067993-e82898af-0409-4a16-8b40-506a6347681b.png)
После
![image](https://user-images.githubusercontent.com/61343836/194067949-736baa7c-b232-4795-a02c-57d7d13bd88f.png)

1)	Пользователь в большинстве случаев взаимодействует с параметрами скорости и качество 1-2 раза за серию, по этой причине нет смысла их выносить на панели и тем самым перегружать интерфейс.
2)	Иконка с выкл. звуком вводит пользователя в заблуждение.
Пользователь должен иметь возможность отмены действия «mute» путём изменения значения trackbar’a
3)	В текущем виде карточка «информация о релизе» не информативна, предлагаю её расширить и вывести основные параметры, такие как: Дата выхода (сезон, год), номер текущей серии и сколько их, список войсеров, день выхода, если имеется.
4)	Кнопку «Пропустить опенинг» выровнять по правому краю, так как это привычное для пользователя место по множеству других сервисов. (например: youtube, кинопоиск и сайт AniLibria). 
5)	Список серий следует ограничить по высоте и выровнять по центру, чтобы пользователь не тянулся каждый раз в угол приложения.
6)	Время надо разделить на два отельных показателя (текущее и всего) и расположить их по разным сторонам или оставить два в одном с одной стороны.
7)	Действие «назад» esc должно возвращать пользователя не в каталог, а на страницу релиза.
8)	До того, как видеопоток загрузился, стоит блокировать кнопки мультимедиа, а не скрывать их.  
9)	Переход в режим «PiP» при действии «назад» является неожидаемым действием для большинства пользователей, поэтому данный функционал следует сделать опциональным и по умолчанию выключить.

**Comment by trueromanus** [comment]
Здравствуйте, спасибо за Ваши предложения, позвольте высказать свое мнение о них и задать вопросы.

1.1 "Название релиза, альтернативное название нет надобности +- одного размера с основным, так как для большинства пользователей оно не является важным." - можно узнать каким образом Вы получили эти статистические данные про большинство пользователей? Ситуация с размером шрифта может выйти боком из-за того что количество вариантов где он может отображаться начиная от форм-факторов операционных систем мониторов и т.п. Т.е. ок я увеличил шрифт для заголовка и уменьшил для второго заголовка в какой-то конфигурации он будет слишком большим из-за dpi и размера монитора где-то наоборот. В темной теме заголовок и второй заголовок одинакового цвета поэтому возможно кажется что здесь что-то не так но в светлой они разных цветов и заголовок сразу читается.
1.2 "Количество торрентов не несёт какой-либо полезной информации" - изначально их не было но т.к. люди просили то количество было добавлено. Насчет выравнивания кнопки подумаю.
1.3.1 Да уже убрано в следующей версии не будет.
1.3.2 "Так как превью серий генерируются не из начала видео как в большинстве плееров, а в случайном месте видео возникает возможность словить спойлер в момент выбора серии" - спойлер по одному кадру из 20 минутной серии это примерно как иголка в стоге сена :) "по этому для компактности списка серий и избежания выше описанного случая, предлагаю использовать стандартный список серий" - ну смотрите я открываю и вижу постеры, постеры занимают нормально пространства, плюс они сразу отражают суть элемента. Список который предлагаете Вы подразумевает не экономию а наоборот, будет полэкрана реально пустым потому что расстояние между текстом "Серия Х" и кнопками качества в окне открытом с расширением 1280х800 выше будет банально содержать ничего. Даже в Вашем примере уже это выглядит как пустая трата пространства. Выбор качества видео прямо в списке был когда-то еще в приложении Win10 и после многочисленных рассуждений с разными пользователями пришло понимание что большинство (и это реально подтверждено моей статистикой) пользователей не меняют качество практически никогда, т.е. они поставили условно 720 и практически никогда его не меняют. У Вас какой кейс? После каждого просмотра Вы выбираете другое качество каждый раз?
2.1 "Страница расписания, в текущем виде, данная страница не пригодна для использования, так как релизы просто отсортированы, но никак не разделены, для исправления данной проблемы предлагаю добавить разделители с подписью дня недели." это уже есть в очереди на реализацию. Впрочем обычно люди через некоторое время привыкают потому что учатся пользоваться сортировкой и фильтрами :)
2.2 "Чтобы с экономить место и увеличить зону поиска предлагаю воспользоваться пустым пространством в шапке страницы и разместить там поиск, а процесс синхронизации отображать путём вращения значка синхронизации на навигационной панели. Также хотелось бы иметь возможность выделять текст в поисковой строке." На том месте в компактном режиме стоит кнопка открытия меню так что экономии не произойдет. А что текст не выделяется в поисковой строке? (а наверно с мышки не выделяется ок добавим) 
3.1 "Пользователь в большинстве случаев взаимодействует с параметрами скорости и качество 1-2 раза за серию, по этой причине нет смысла их выносить на панели и тем самым перегружать интерфейс." Откуда такие статистические данные? :).
3.2 "Иконка с выкл. звуком вводит пользователя в заблуждение.
Пользователь должен иметь возможность отмены действия «mute» путём изменения значения trackbar’a" Какого пользователя и почему в заблуждение? :) О каком trackbar-е речь?
3.3 "В текущем виде карточка «информация о релизе» не информативна, предлагаю её расширить и вывести основные параметры, такие как: Дата выхода (сезон, год), номер текущей серии и сколько их, список войсеров, день выхода, если имеется." - Вы случаем не из Win10 приложения пришли? Там как раз была такая плашка но так вышло что после многочисленных обсуждений с разными пользователями пришли к выводу что вся эта инфа мало кому нужна и она жрет кучу места в окне. Опять же тут какой кейс я во время просмотра вдруг захочу узнать дату выхода и день в расписании, количество серий и какая активная и так есть в левой панели.
3.4 "Кнопку «Пропустить опенинг» выровнять по правому краю, так как это привычное для пользователя место по множеству других сервисов. (например: youtube, кинопоиск и сайт AniLibria)." - ук подумаю над этим
3.5 "Список серий следует ограничить по высоте и выровнять по центру, чтобы пользователь не тянулся каждый раз в угол приложения." - это тоже было в Win10 приложении и тоже проходили. Сейчас оно растет по высоте т.е. если серий много то оно будет растягиваться вплоть до нижней контрольной панели. Насчет тянутся в большинстве своем туда тянутся и не надо потому что навигация вперед/назад есть в панели, плюс есть клавиатурные shortcut-ы плюс есть автоматический переход между сериями т.е. прям каждый раз тянутся к панели не надо.
3.6 "Время надо разделить на два отельных показателя (текущее и всего) и расположить их по разным сторонам или оставить два в одном с одной стороны." - а сейчас не так?
3.7 "Действие «назад» esc должно возвращать пользователя не в каталог, а на страницу релиза." - для этого уже есть настройка
3.8 "До того, как видеопоток загрузился, стоит блокировать кнопки мультимедиа, а не скрывать их." - к сожалению есть технические ограничения из-за которых пришлось скрывать кнопки :(
3.9 "Переход в режим «PiP» при действии «назад» является неожидаемым действием для большинства пользователей, поэтому данный функционал следует сделать опциональным и по умолчанию выключить." - опять большинство пользователей :) Вы первый кто об этом пишет хотя эта фича уже версий 6 назад была сделана.

**Comment by Dezexus** [comment]
1.1
  1.1.1 Фиг с этим цветом в тёмной теме.
  1.1.2 Вот скажу как, есть я не знаток Qt и особенностях его работы с шрифтом в разных условиях, так что разрешаю меня проводить за дверь, но это же не первое приложение на нём и почему-то в других разные размеры уживаются, как минимум второе приложение AL (вроде оно тоже на Qt), так почему здесь оно должно кардинально все переломить?
  1.1.3 С чего я взял, что альтернативное название менее важное? (Далее сарказм, аккуратно) Даже не знаю, с чего бы в русском сервисе, с русскоязычной аудиторией, в приложении на русском, японское название было менее важным? Понятие не имею, с чего я так подумал. 
1.2
Ну если запрос пользователей был, то не смею возражать (хоть мне и любопытно зачем им это).
1.3.2
  1.3.2.1 Я согласен с тем, что я не учёл мелкие разрешение (например 1280х800), в данном случаи действительно список проигрывает.
  1.3.2.2 С качество я жёстко промахнулся, не знаю с чего я взял, что оно не сохраняется, прошу прощение, но вашу речь я процитирую на пару вопросов ниже.
  1.3.2.3 Тогда пусть остаются превью с номером, но тут появляется несколько других пунктов
    1.3.2.3.1 Можно обернуть список серий не в List, а во WrapPanel (не знаток Qt, в общем список с переносом не помещающего контента на следующую строку), это позволит нормально взаимодействовать со списком серий как на маленьких разрешениях, так и не терять куча свободного пространства на больших экранах.
    1.3.2.3.2 Конкретно про текущие проблемы на маленьких экранах: не работает скрол мышью у списка серий, страница не имеет прокрутки, по этой причине весь контент страницы не помещается на маленьких разрешениях.
    1.3.2.3.3 Данных пункт субъективен, но по-моему, текущий размер превью великоват и может быть уменьшен на ~20%.
2.1
Можно привыкнуть ко всему, а можно иметь из коробки, а не привыкать.
2.2
Может экономии и не произойдёт, но ux поиска однозначно вырастет, ведь поиск — это не та вещь, которой ты пользуешься по праздникам и его область кликабельности (не надумал более подходящего слова) важна. Хотя конечно, подозреваю, что там есть техническая не приятная сторона. За выделение текста заранее спасибо. 
3.1
Простите, но тут лучше вас (на несколько вопрос выше) никто не скажет.
«Выбор качества видео прямо в списке был когда-то еще в приложении Win10 и после многочисленных рассуждений с разными пользователями пришло понимание что большинство (и это реально подтверждено моей статистикой) пользователей не меняют качество практически никогда, т.е. они поставили условно 720 и практически никогда его не меняют.»
Ещё имеются вопросы, почему я считаю, как минимум качество видео, а я уверен, что со скоростью статистика ещё примечательней, нерациональным выносить данные параметры на поверхность и перегружать ими интерфейс?
3.2
Простите за прямолинейность, а с чего он не должен вводить в заблуждение, если нас с “детства” приучают, что колонка со волнами звук есть, без – нету, всю жизнь это все сервисы используют в первую очередь как индикатор, а во 2-ю как кнопку mute. Под trackbar’om я умею ввиду ползунок громкости. 
3.3
  3.3.1 Приложением для win10 пользовался и знаю о функции, но никогда ей там не пользовался.
  3.3.2 А придирка в том, что вы называете данный функционал как «Информация о релизе» и какую же информацию несёт постер? Раз уж пользователи решили, что нет, то стоило бы и вовсе вырезать данный функционал, а я лишь попробовал изобразить, то что написано в функции «информация…» (хотя дата выхода была излишней).
3.5
И снова вы мыслите по принципу «сейчас и здесь» потянулся там, потянулся здесь и ещё пару раз и растянулся, тогда легче сразу в Дыбу залезть. И опять же тема с разными экранами у кого-то ведь не маленький экран, может показаться, что это же плюс сколько серий за раз видно, но человек не фокусируется на все объекты по горизонту, а лишь в одной конкретной точке, и по итогу места занимает дофига, а пользы ~0.
3.6
У вас слева расположен вариант 2в1 и плюс справа сколько всего. А я предлагаю либо оставить только 2в1, либо слева текущая позиция, а справа всего.
3.9
А здесь я запрошу разъяснение по данному функционалу. На моём устройстве при выходе через esc из плеера появляется мини плеер, а на другом нет, как это работает?

**Comment by trueromanus** [comment]
Здравствуйте,
1.1.2 Хорошо я увеличил шрифт заголовка если это такая драма :)
1.1.3 Альтернативное название было добавлено по просьбам пользователей, и даже поиск по альтернативному названию был добавлен по тем же причинам.
1.2 Не поверите потому что люди разные и разным людям нужны разные вещи
1.3.2.* Давайте так, суть этого списка была именно в наличии постеров для каждой серии. Этот список появился буквально пару версий назад и до этого его не было был просто выбор серии. Суть этого списка и была в том чтобы использовать постеры. Вы предлагаете продублировать список серий который и так есть на странице видеоплеера еще и добавить в него выбор качества. И серии и качество уже есть на другой странице, просто открыл и меняй.
1.3.2.3.2 "Конкретно про текущие проблемы на маленьких экранах: не работает скрол мышью у списка серий, страница не имеет прокрутки, по этой причине весь контент страницы не помещается на маленьких разрешениях." Для этого надо зажать Alt/Cmd
"2.1 Можно привыкнуть ко всему, а можно иметь из коробки, а не привыкать." Если бы такое можно было сделать "из коробки" то оно бы уже было сделано.
"2.2 Может экономии и не произойдёт, но ux поиска однозначно вырастет, ведь поиск — это не та вещь, которой ты пользуешься по праздникам и его область кликабельности (не надумал более подходящего слова) важна. Хотя конечно, подозреваю, что там есть техническая не приятная сторона." а область "кликабельности" остальных элементов не важна? :) Специально чтобы меньше пользоваться поиском было сделана куча заранее подготовленных списков, уведомлений и страница "Моя Анилибрия".
"Ещё имеются вопросы, почему я считаю, как минимум качество видео, а я уверен, что со скоростью статистика ещё примечательней, нерациональным выносить данные параметры на поверхность и перегружать ими интерфейс?" Я может пропустил что-то но раз Вы предлагаете что-то убрать то куда и как это должно работать?
"3.2 Простите за прямолинейность, а с чего он не должен вводить в заблуждение, если нас с “детства” приучают, что колонка со волнами звук есть, без – нету, всю жизнь это все сервисы используют в первую очередь как индикатор, а во 2-ю как кнопку mute. Под trackbar’om я умею ввиду ползунок громкости." ок подумаю над этим
"А придирка в том, что вы называете данный функционал как «Информация о релизе» и какую же информацию несёт постер? Раз уж пользователи решили, что нет, то стоило бы и вовсе вырезать данный функционал, а я лишь попробовал изобразить, то что написано в функции «информация…»" постер перестал входить в информацию о релизе? как минимум в нем есть картинка и название :) И опять же Вы критикуете но предложений не вижу.
"3.5 И снова вы мыслите по принципу «сейчас и здесь» потянулся там, потянулся здесь и ещё пару раз и растянулся, тогда легче сразу в Дыбу залезть. И опять же тема с разными экранами у кого-то ведь не маленький экран, может показаться, что это же плюс сколько серий за раз видно, но человек не фокусируется на все объекты по горизонту, а лишь в одной конкретной точке, и по итогу места занимает дофига, а пользы ~0." опишите конкретную проблему с которой Вы столкнулись и я попробую ее решить, то что Вы написали это просто поток сознания. И да не надо пытаться решать проблемы мифического пользователя. Если "человек не фокусируется на все объекты по горизонту, а лишь в одной конкретной точке" то что решит небольшое уменьшение высоты этого списка?
"3.9 А здесь я запрошу разъяснение по данному функционалу. На моём устройстве при выходе через esc из плеера появляется мини плеер, а на другом нет, как это работает?" это зависит от операционной системы и их версий

**Comment by Dezexus** [comment]
1.3.2.3.2 «Для этого надо зажать Alt/Cmd», вверх интуитивности.
«"Ещё имеются вопросы, почему я считаю, как минимум качество видео..." Я может пропустил что-то но раз Вы предлагаете что-то убрать то куда и как это должно работать?» 
Переместить их в выпадающее меню, в две отдельных кнопки
 
![image](https://user-images.githubusercontent.com/61343836/194723099-7386b0a3-3e70-495e-9322-aae48a90b7cb.png)


«"А придирка в том, что вы называете данный функционал как «Информация о релизе» …" постер перестал входить в информацию о релизе? как минимум в нем есть картинка и название :) И опять же Вы критикуете но предложений не вижу.»
Я своё предложение как раз таки сделал: 1) действительно добавить информацию, 2) Удалить данный функционал.

**Comment by trueromanus** [comment]
"1.3.2.3.2 «Для этого надо зажать Alt/Cmd», вверх интуитивности." - дак это не я придумал это так ОС Microsoft работает и не только она :)
"Переместить их в выпадающее меню, в две отдельных кнопки" - я уже написал почему что-то выпадающее убивает ux в этом месте, выпадайки для настроек это скорее костыль чем адекватное решение да и их открывают крайне редко.
"Я своё предложение как раз таки сделал: 1) действительно добавить информацию, 2) Удалить данный функционал." - чем Вам не угодила эта панелька? :) Ну если Вам (и другим кому она не нужна) не нужна ну ок можно скрыть ее, есть настройка для этого. Я думал Вы докапались до названия и предложите другое но удаляться точно ничего не будем.

**Comment by trueromanus** [comment]
Сводка по тому что было сделано:
- Увеличен размер шрифта для текста заголовка названия релиза в карточке релиза (в версии 1.2.0)
- Возможность выделять текст с помощью мыши (в версии 1.2.0)
- Переделана кнопка mute, теперь она не окрашивается а меняет иконку (в версии 1.2.0)
- Изменение ползунка громкости выключает mute если он был включен (в версии 1.2.0)
- Кнопка "Пропустить Опенинг" сдвинута к правой части окна (в версии 1.2.1)
- Добавлена настройка "Выравнивание списка серий по центру" (в версии 1.2.1)

**Comment by trueromanus** [comment]
Итак возвращаясь к нашему обсуждению, выносить ли качества и скорости в выпадающие кнопки. Я правильно понимаю что Вы подразумеваете что иконки на этих кнопках будут указывать на текущее состояние т.е. для качеств это текущее выбранное качество, для скорости текущую скорость, я все правильно понял?

**Comment by Dezexus** [comment]
Да, как вариант.

**Comment by trueromanus** [comment]
Проблема в том что набора иконок для этого нет (если я и найду что-то, то это будет из разных наборов выглядящее не однородно). Может Вы поможете с этим?

**Comment by trueromanus** [comment]
Последняя проблема вынесена в отдельное ишью #94.
