### ISSUE TITLE
Проблемы с цветами в тёмной теме

### ISSUE THREAD

**Issue by Dezexus** [anilibria/anilibria-winmaclinux#89]
1) Белая заливка в выпадающем списке уведомлений при тёмной теме, когда список пуст
 
![image](https://user-images.githubusercontent.com/61343836/194068635-91e3456e-7c10-4c7f-a5a9-5bfd33cc465e.png)

2) Для затемнения фона, используется светлый оттенок
 
![image](https://user-images.githubusercontent.com/61343836/194068646-5bb27d48-680e-4cdc-9c69-30b121d7c15c.png)

**Comment by trueromanus** [comment]
1. Исправлено и войдет в следующую версию
2. Это утверждение или намек на что-то?

**Comment by Dezexus** [comment]
2. Это утверждение, текущая заливка фона, перечит тёмной теме, должен быть чёрный цвет.

**Comment by trueromanus** [comment]
Сейчас я сделал то что выше 80% прозрачности и по идее особых различий нет. Все что выше 80% уже слишком темно становится.  
Изменение войдет в версию 1.1.13. Но дискуссию можно продолжать в случае надобности :)
