### ISSUE TITLE
Вопросы со сборкой пакета

### ISSUE THREAD

**Issue by WaffleLapkin** [anilibria/anilibria-winmaclinux#9]
Я попытался сделать пакет для Arch Linux (`PKGBUILD`) и столкнулся с несколькими проблемами:
1. Путь установки задан `/opt/AniLibria/bin/AniLibria`, в то время как в Arch linux обычно используется `/usr/bin/<...>`. Честно сказать не знаком с qt и .pro файлами, но судя по тому, что я нагуглил - чтобы поддерживать override пути установки, надо добавить что-то такое в `.pro` файл:
   ```
   target.path = $${PREFIX}}/AniLibria
   INSTALLS += target
   ```
   (взято из ответа 2010 года: https://lists.qt-project.org/pipermail/qt-interest-old/2010-February/018490.html)

   Или можно как-то просто через аргументы командной строки для `qmake` это изменить? Я не нашёл такого способа, но было бы здорово.

1. Название достаточно длинное и странное, имхо. Оно временное, или так всегда и будет `...-winmaclinux`?

**Comment by trueromanus** [comment]
1. в AniLibria.pro файле есть на 47 строке
```
else: unix:!android: target.path = /opt/$${TARGET}/bin
```
Можно заменить путь на необходимый, условия конкретно для arch linux я не уверен что есть.
2. Название как название, в чем с ним проблема?

**Comment by WaffleLapkin** [comment]
1. Условие конкретно для arch linux не нужно, нужна возможность заменить этот путь при вызове `qmake`. Ну да ладно, патчить так патчить :)
2. Просто ни разу не встречал приложений с перечислением операционных систем под которыми они работают.

**Comment by trueromanus** [comment]
Через qmake я не нашел как это сделать, вроде как идея qmake как раз в наличии pro файла который должен все разрулить :(
Имя такое потому что в тиме так принято называть репы, в будущем может переименуем во чтонибудь типа ..-cp или ..-desktop

**Comment by trueromanus** [comment]
Кстати если пакет выйдет пожалуйста отпишись здесь или в новой ишью, чтобы можно было составить список для каких дистров сделаны пакеты с постоянным списком мейнтенеров.
