### ISSUE TITLE
Плеер

### ISSUE THREAD

**Issue by Dezexus** [anilibria/anilibria-winmaclinux#91]
1)	Он плохо преносит большое (не более 5) кол-во перемоток, после нескольких перемоток может остановиться и больше не загружать видеопоток. (пару раз вовсе приложение вылетело)
2)	Судя по всему, он крайне плохо переваривает нестабильный поток (когда загружены сервера)
Вообще он крайне нестабильный, и с моим интернетом это не связано (150-200 Мбит/с), а у другого пользователя (скорость 6 Мбит/с) по описанию, так же, раньше он пользовался старым приложение под Win 10, где таких проблем не было.

1. Пк
- intel i5 10400f
- ОП 16Gb 2666
- Geforce RTX 3070
- Window 11 22621.608

2. Пк
- intel i5 4670
- ОП 8Gb
- Geforce RTX 1050ti
- Window 10 19043.2006

**Comment by trueromanus** [comment]
Здравствуйте, к сожалению ~~мопед не мой~~ плеер делал не я. Сделать свой плеер это конечно же интересная задача но крайне амбициозная и требующая прорву времени. Я выбирал из того что было, этот подходил лучше всех. Если у Вас прям совсем невыносимо смотреть онлайн в приложении можете попробовать смотреть в любом другом плеере типа VLC, MPC-HC и т.п. (для открытия в этих плеерах есть специальный пункт в карточке релиза) а также недавно появилась возможность открыть серии в веб-браузере. В общем недостатки плеера компенсируются возможностями смотреть в других вариантах. К сожалению что-то сделать с плеером невозможно.
