### ISSUE TITLE
Свертывание окна в режиме кастомного тулбара

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#92]
Система: Linux 5.10.139 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Воспроизведение:
Заходим в "Настройки страницы Каталог Релизов" включаем "Использовать кастомный тулбар", выходим из настроек. Нажимаем кнопку в тулбаре "Открыть окно на полный экран" (стрелочки иконки кнопки направлены в противоположные стороны), окно раскрывается на весь экран, картинка на кнопке "Открыть окно на полный экран" меняется на стрелки направленные друг к другу. Далее нажимаем кнопку "Минимизировать окно в панель задач" окно сворачивается. Затем нажимаем на свернутое приложение и оно  раскрывается не в полноэкранном режиме, а с размером до него, однако иконка в тулбаре кнопки "Открыть окно на полный экран" показывает стрелки направленные друг к другу то есть приложение считает что оно находится в полноэкранном режиме. Нажимаем на кнопку "Открыть окно на полный экран" ничего не происходит, но иконка меняется на стрелки в разные стороны, еще раз нажимаем и окно раскрывается на экран.

Похоже приложение не сохраняет развернутый экран после сворачивания его кнопкой "Минимизировать окно в панель задач", хотя судя по значку и его поведению оно должно это делать.

**Comment by trueromanus** [comment]
Спасибо за обращение.
Я бы не рекомендовал использовать кастомный тулбар на Linux.

**Comment by trueromanus** [comment]
Вероятный фикс добавлен и войдет в версию 1.2.1.

**Comment by Koi-foo** [comment]
> Я бы не рекомендовал использовать кастомный тулбар на Linux.
> Вероятный фикс добавлен и войдет в версию 1.2.1.

Ясно спасибо.
