### ISSUE TITLE
Затемнение экрана при просмотре видео

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#93]
Система: Linux 5.10.139 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Затемнение экрана при длительном просмотре видео. Я не знаю как это правильно называется, но вовремя просмотра видео срабатывает режим энергосбережения, то есть плеер должен давать какую-то эмуляцию деятельности (назову это пинанием) чтобы дать понять системе о своей работе, без этого она считает что система бездействует и начинает затемнять экран, потом его тушить и постепенно переходит в сон.

**Comment by trueromanus** [comment]
Добавлено, изменение войдет в версию 1.2.1.
Проверено только на гноме, кед под рукой нет, поэтому если возможно соберите из исходников и проверьте что на кедах тоже норм. Ну или Вы можете подождать версию и если не будет работать переоткройте пожалуйста эту ишью.

**Comment by Koi-foo** [comment]
> Добавлено, изменение войдет в версию 1.2.1. Проверено только на гноме, кед под рукой нет, поэтому если возможно соберите из исходников и проверьте что на кедах тоже норм. Ну или Вы можете подождать версию и если не будет работать переоткройте пожалуйста эту ишью.

Пересобрал. Исправлено, спасибо.
