### ISSUE TITLE
Лишний переключатель в меню настройки

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#95]
Система: Linux 5.10.139 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Заметил что в версии 1.2.1 появился лишний переключатель, посмотрел старые версии оказывается он появился в 1.2.0 просто не замечал, поставил архивную версию 1.1.12 в ней нет меню темы, зато есть их переключатель, наверное его поменяли на меню, а видимо переключатель остался.
![Screenshot_20221104_142357-2](https://user-images.githubusercontent.com/11571779/199965309-c4778165-c324-4f0c-9dc6-3d0b97de38c4.png)
На скриншоте я его отметил красным квадратом.

Сопутствующий вопрос, кнопка "Сделать страницу стартовой" похоже ничего не делает?

**Comment by trueromanus** [comment]
Отлично подмечено, спасибо! 
"Сопутствующий вопрос, кнопка "Сделать страницу стартовой" похоже ничего не делает?" - она не активна скорей всего а вообще это кнопка нужна чтобы вернуть стартовую страницу каталог релизов, также можно стартовой сделать страницу "Моя Анилибрия". Стартовой т.е. той которая открывается сразу после запуска приложения.
