### ISSUE TITLE
Кнопка "Открыть окно на полный экран" не возвращает окно в исходную форму

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#96]
Система: Linux 5.10.139 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Как воспроизвести.
Открываем приложение не в полноэкранном режиме. Нажимаем кнопку "Открыть окно на полный экран" в "Тулбаре". Окно раскрывается на весь экран. Нажимаем кнопку "Выйти из приложения" в "Тулбаре". Программа закрывается. Снова открываем приложение. Приложение открывается на весь экран. Нажимаем на туже кнопку "Вернуть окну нормальный размер" иконка кнопки меняется, но с окном ничего не происходит. Похоже запоминаются только текущие размеры окна, а те что были до закрытия стираются, хотя установка окна в полноэкранном режиме сохраняется после перезапуска приложения. Это не очень удобно потому что приходится использовать стрелки чтобы вернуть окну нормальный вид.

**Comment by trueromanus** [comment]
Исправлено и войдет в версию 1.2.2
