### ISSUE TITLE
Ошибка сегментирования при закрытии программы.

### ISSUE THREAD

**Issue by Koi-foo** [anilibria/anilibria-winmaclinux#97]
Система: Linux 5.10.139 х64
DE: KDE 5.24.6
QT: 5.15.4
Х-Сервер: x11

Воспроизведение.
Запустить программу в терминале.
`$ AniLibria`
Выйти из программы через кнопку "Выйти из приложения", после этого в терминале появляется сообщение.
`Ошибка сегментирования`
Само приложение работает нормально, проблем с вылетами нет, других сбоев тоже не замечено, похоже что эта ошибка происходит только вовремя закрытия.

Буфер ядра об этом событии пишет так:
`AniLibria[5731]: segfault at 55c7fff4189c ip 00007ffa7b8c855a sp 00007ffe07639160 error 4 in libQt5Multimedia.so.5.15.4[7ffa7b83e000+8d000]`
Похоже на неверную переменную.

**Comment by trueromanus** [comment]
Здравствуйте о проблеме известно и я исправить ее не в состоянии. Подробнее [тут](https://github.com/anilibria/anilibria-winmaclinux/issues/79)
