### ISSUE TITLE
Не воспроизводится видео после сборки

### ISSUE THREAD

**Issue by Jaymz665** [anilibria/anilibria-winmaclinux#98]
Не воспроизводится видео, собрано на двух arm платформах Pmos (alpine arm64) и Ubuntu  (armbian arm64). Сборка происходит без сучка и задоринки, приложение открывается корректно, все загружается, но при попытке запустить любую серию я вижу бесконечно крутящийся значок. Стоит отметить, что чуть больше полугода назад я так же собирал anilibriaqt на armbian и всё работало безупречно.

**Comment by trueromanus** [comment]
К сожалению армов у меня нет и проверить как там оно не могу. Но тем не менее приложение не само воспроизводит видео а использует компоненты из системы на Linux это обычно gstreamer (но может быть и что-то другое зависит от сборки). Начать стоит как минимум с того что запустить приложение из консоли и проверить пишутся ли там ошибки после попытки воспроизвести видео.

**Comment by Jaymz665** [comment]
Терминал на Pmos выдал 
qml: InvalidMedia
Error: "Видео-устройство использует неподдерживаемый пиксельный формат."

> К сожалению армов у меня нет и проверить как там оно не могу. Но тем не менее приложение не само воспроизводит видео а использует компоненты из системы на Linux это обычно gstreamer (но может быть и что-то другое зависит от сборки). Начать стоит как минимум с того что запустить приложение из консоли и проверить пишутся ли там ошибки после попытки воспроизвести видео.

**Comment by Jaymz665** [comment]
По ubuntu arm, действительно, хоть GStreamer1 был помечен как установленный, ему не хватало библиотек, полная переустановка пакета это исправила

**Comment by trueromanus** [comment]
> Терминал на Pmos выдал
> qml: InvalidMedia
> Error: "Видео-устройство использует неподдерживаемый пиксельный формат."
Скорее всего тоже не хватает кодеков или каких-то пакетов. Ошибка InvalidMedia подразумевает что не поддерживается чтение или воспроизведение медиа файла.

**Comment by trueromanus** [comment]
Да видимо на pmos видеоплеер  не работает, как вариант предлагаю Вам смотреть в VLC плеер. Для этого в карточке релиза нажмите на самую нижнюю кнопку иконку со стрелочкой в правой части экрана. Там будет меню с выбором качества, выбирайте из трех верхних пунктов. После нажатия на одного из приложение сгенерит файл плейлиста m3u8. Этот файл можно открыть в VLC и смотреть как плейлист.

**Comment by trueromanus** [comment]
В последней версии появилась интеграция с плеером VLC который точно будет работать хорошо.
